### ISSUE TITLE
Call to Appboy.wipeData results in a exception

### ISSUE THREAD

**Issue by quiro91** [Appboy/appboy-android-sdk#100]
# Report

## What version of the Braze Android SDK are you using?

2.3.0

## What did you do?

Calling the method `AppBoy.wipeData(Context context)` results in the following exception: 
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/location/LocationServices;
```

## What did you expect to happen?

It shouldn't fail because of anything location related. I think that probably adding the dependency would just fix it but I'd rather not do that

## What happened instead?

it does fail

## Steps to reproduce

I guess you just need a project that doesn't use google play services location

**Comment by radixdev** [comment]
Hello @quiro91 ,

Thanks for filing this issue. We've marked this as a highest-priority bug and should have a fix ready shortly.

**Comment by radixdev** [comment]
Version 2.4.0 was released, containing the fix. 

Please let us know if this fixes your issue.

**Comment by quiro91** [comment]
Looks like it's working! Thanks for the quick fix!
