### ISSUE TITLE
Appboy crashes

### ISSUE THREAD

**Issue by veerenmandalia** [Appboy/appboy-android-sdk#101]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
2.2.4

## What did you do?
Seeing user crash reports (60 per week)

Using appboy via mParticle.
mParticle version: 4.17.12
mParticle appboy kit: 4.17.12

mParticle uses [appboy 2.2.4](https://github.com/mparticle-integrations/mparticle-android-integration-appboy/blob/581d82c0e49c0a952560749f99ca2df4d438f6c1/build.gradle) in that [kit version](https://github.com/mParticle/mparticle-android-sdk/tree/v4.17.12/kits)

## What did you expect to happen?

Not crash

## What happened instead?

Crash

## Steps to reproduce

Unsure, see crash reports
[crash_1_activity_stop.txt](https://github.com/Appboy/appboy-android-sdk/files/2037612/crash_1_activity_stop.txt)
[crash_2_activity_resume.txt](https://github.com/Appboy/appboy-android-sdk/files/2037613/crash_2_actiity_resume.txt)

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

Don't think so, the only customizations are having a Appboy Gcm Receiver with some logging.

## Project that demonstrates the issue

Don't have one

**Comment by Bucimis** [comment]
Hi @veerenmandalia,

Thanks for getting in touch. This issue was fixed in SDK version 2.2.5 (see https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#fixed-2). If you upgrade your SDK, you should no longer see these crashes.

Thanks,
Braze SDK Engineering

**Comment by radixdev** [comment]
Hey @veerenmandalia ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
