### ISSUE TITLE
I can't get a colored notification to show on api level 26 and higher

### ISSUE THREAD

**Issue by alexandru-calinoiu** [Appboy/appboy-android-sdk#103]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
2.5.0

## What did you do?

I've set `com_appboy_push_small_notification_icon` drawable according to the docs and pointed it to a color image

## What did you expect to happen?

The image that I set to show up as notification icon

## What happened instead?

I see a gray square instead of the icon I set in the top bar and it in the notification panel

![screenshot_20180703-204855](https://user-images.githubusercontent.com/679198/42236269-1ad8b4a0-7f03-11e8-8d69-c80c8bd47665.png)
![screenshot_20180703-204929](https://user-images.githubusercontent.com/679198/42236270-1b1103e6-7f03-11e8-9b9d-d135bafa201f.png)

## Steps to reproduce

- Add a colored icon 
- start the app on stock andorid 8 (v26) or later 
- send a test notification

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
no

## Project that demonstrates the issue

none

**Comment by radixdev** [comment]
Can you share the icon used (attach here / link)?
Additionally, can you confirm that the icon used conforms to the notification requirements as set [here](https://developer.android.com/about/versions/android-5.0-changes#BehaviorNotifications)? 
Namely: 
![image](https://user-images.githubusercontent.com/2373546/42236923-501172b2-7eca-11e8-898e-583bff17d2ed.png)

**Comment by alexandru-calinoiu** [comment]
Got it, my icon does not respect those requirements.

**Comment by alexandru-calinoiu** [comment]
Got it, my icon does not respect those requirements.
