### ISSUE TITLE
Improve compatibility with Kotlin using nullability annotations

### ISSUE THREAD

**Issue by sergiandreplace** [Appboy/appboy-android-sdk#105]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?

2.4.0

## What did you do?

We have seen some crashes due to Appboy.getCurrentUser() returning null, and this was not expected.

## What did you expect to happen?

As we are using Kotlin, we expect the getCurrentUser to be annotated with @Nullable in order to know if it's a nullable value or not

## What happened instead?

Kotlin has no information about nullability

## Steps to reproduce

Just invoke Appboy.getcurrentUser from kotlin

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

Using Kotlin? ¯\_(ツ)_/¯

## Project that demonstrates the issue

Sorry, can't share code

**Comment by AlbertVilaCalvo** [comment]
Building Kotlin friendly APIs - Interoperability
https://www.youtube.com/watch?v=fWuzGonOM1c

**Comment by radixdev** [comment]
Hello @sergiandreplace ,

Thanks for filing this issue. I've added this as a high priority issue for our SDK roadmap. 

Cheers,
Julian

**Comment by sergiandreplace** [comment]
Great! Thanks Julian!

**Comment by radixdev** [comment]
Hello @sergiandreplace , 

Apologies for the delay on this one. We've released SDK version 3.0.0, which contains nullability annotations for Kotlin. Please let me know if this solves your issue.

Julian

**Comment by radixdev** [comment]
I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
