### ISSUE TITLE
Support for AndroidX

### ISSUE THREAD

**Issue by dannyroa** [Appboy/appboy-android-sdk#107]
We are trying to migrate to AndroidX but with AppBoy not supporting it, we are blocked.

Thanks.

**Comment by radixdev** [comment]
Hello @dannyroa ,

Thanks for the feedback. Adding support for AndroidX is one of our top priorities. We are currently working on AndroidX compatibility but don't have any firm release dates at this time. What specific errors/blockers are you seeing?

Thanks,
Julian

**Comment by dannyroa** [comment]
@radixdev AppBoy SDK has dependence on Support Library. In our code, we replaced all Fragments, Activities with the androidx version. However, the AppBoy SDK are still using the Support version.

You can see the class mappings at https://developer.android.com/topic/libraries/support-library/refactor.

Running the dependencies task give me this:

```
|    +--- com.appboy:android-sdk-ui:2.1.0
|    |    +--- com.appboy:android-sdk-base:2.1.0
|    |    \--- com.android.support:support-v4:26.0.0 -> 26.1.0
|    |         +--- com.android.support:support-compat:26.1.0 (*)
|    |         +--- com.android.support:support-media-compat:26.1.0
|    |         |    +--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         |    \--- com.android.support:support-compat:26.1.0 (*)
|    |         +--- com.android.support:support-core-utils:26.1.0
|    |         |    +--- com.android.support:support-annotations:26.1.0 -> 27.1.1
|    |         |    \--- com.android.support:support-compat:26.1.0 (*)
|    |         +--- com.android.support:support-core-ui:26.1.0 (*)
|    |         \--- com.android.support:support-fragment:26.1.0
|    |              +--- com.android.support:support-compat:26.1.0 (*)
|    |              +--- com.android.support:support-core-ui:26.1.0 (*)
|    |              \--- com.android.support:support-core-utils:26.1.0 (*)
```

Thanks.

**Comment by quiro91** [comment]
I'm having some issues in the migration to AndroidX because of AppBoy too. In my case using `AppboyNotificationFactory.populateNotificationBuilder` returns a instance of `android.support.v4.app.NotificationCompat.Builder` while I'd need `androidx.core.app.NotificationCompat`

**Comment by radixdev** [comment]
Hello @dannyroa ,

Apologies for the delay. We have an AndroidX compatibility module developed and are actively testing to ensure the SDK is completely compatible with AndroidX. 

In the meantime, a few more questions:
1. Does Jetifier, `android.enableJetifier=true 
android.useAndroidX=true` not convert our support dependencies properly in your build?
2. Are there specific fragments/activities from the SDK that are not compatible after enabling Jetifier?

**Comment by dannyroa** [comment]
Jetifier doesn't work for us. Looks like it's because of Dagger.

Jetifier also does not work for the version of the Android Gradle plugin that we're using.

**Comment by dannyroa** [comment]
Dagger 2.8
AGP 3.2.0

So you want to debug our Dagger issues with Jetifier? It has nothing to do with AppBoy since it is not part of our Dagger code.

I honestly want to avoid using Jetifier until it's stable and would prefer to use libraries that are migrated to AndroidX.

**Comment by radixdev** [comment]
Hello @dannyroa ,

We plan on using Jetifier for AndroidX compatibility in the foreseeable future. Any issues with Jetifier and our SDK I want to try to address, if possible. Apologies for the confusion there.

Our project that we've been using to test the AndroidX compatibility module (using Jetifier) is also on AGP 3.2.0. As for Dagger, is [version 2.16](https://github.com/google/dagger/releases/tag/dagger-2.16) incompatible as well? [In this issue](https://github.com/google/dagger/issues/1188#issuecomment-392138753), it looks like they've added some level of AndroidX support.

If Jetifier is still out of the question, I would recommend forking our [android-sdk-ui](https://github.com/Appboy/appboy-android-sdk/tree/master/android-sdk-ui) project and peforming an imports migration to use AndroidX directly. The base project does not depend on any support-vX libraries, only the UI project.

**Comment by radixdev** [comment]
Yes. Jetifier got us about 90% of the way to compatibility. The rest of the work was adding support for directly using `support.v*.*` classes for our Notification classes (the issue @quiro91 was describing). The solution we're developing uses AndroidX directly for those classes and uses Jetifier to ensure the dependency `android-sdk-ui` library is transformed correctly. 

Note that we _do_ intend on transitioning the SDK over to AndroidX without the use of Jetifier in the future. This aforementioned module will be a transitionary solution until that time.

**Comment by radixdev** [comment]
Hello @dannyroa and @quiro91 ,

We've released SDK 3.0.0, which contains our new `android-sdk-ui-x` compatibility module. Please see the [changelog entry for 3.0.0](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#300) for more information on integrating it. Please note that this compatibility requires the use of Jetifier, as discussed.

Cheers,
Julian

**Comment by quiro91** [comment]
That's great, thanks @radixdev , I'm gonna give it a try

**Comment by radixdev** [comment]
I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
