### ISSUE TITLE
AppBoy to support -> Restrictions on non-SDK interfaces on Android Pie

### ISSUE THREAD

**Issue by KevinLeigh** [Appboy/appboy-android-sdk#109]
As of Android Pie, there is restrictions for using non-SDK interfaces. Please see documentation here -> https://developer.android.com/about/versions/pie/restrictions-non-sdk-interfaces

Will AppBoy be updated to fully support `Restrictions on non-SDK`?

**Comment by Bucimis** [comment]
Hi @KevinLeigh, 

We generally avoid using non-SDK interfaces. Have you seen an instance of greylisted SDK usage logs or blacklisted SDK usage crashes originating from the Braze SDK?

**Comment by KevinLeigh** [comment]
Hey @Bucimis,

I do not find any blacklisted only grey listed please see example one below ->

```
#234: Reflection dark greylist Landroid/net/Credentials;->pid potential use(s):
       Lbo/app/cf;->a(Ljava/lang/String;Ljava/lang/String;Ljava/math/BigDecimal;ILcom/appboy/models/outgoing/AppboyProperties;)Lbo/app/cf;
```

There are a few others as well

**Comment by radixdev** [comment]
@KevinLeigh 
What Braze SDK version was this tested on?
Do you have a list of all the "potential" greylist uses?

This could just be an example of proguard obfuscation confusing the runtime to believe there's a greylist match.

**Comment by radixdev** [comment]
Hey @KevinLeigh ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
