### ISSUE TITLE
Update the unReadCardCount for news feed event doesn't work if we change customer property even after refreshing, only if we restart the activity

### ISSUE THREAD

**Issue by mohamedbrahem** [Appboy/appboy-android-sdk#111]
Hello

we are using the SDK call : mFeedUpdatedSubscriber = event -> runOnUiThread(() -> event.getUnreadCardCount())) to get the unread cards count for the current user. the problem is that once we change the user custom attribute (in our case timeline language), and after requesting a feed refresh (Appboy.getInstance(context).requestFeedRefresh()) the SDK is not refreshing and returning the unreadCardCounter with the previous user attribute. even remove single subscription before fetching data is not working. the only way to get the correct card counter is to close the activity and create it again.

We expect this one to work and return the real value of unread cards, even without removing the single subscription. as we want to update the badge for news feed even if the app user did not open the news feed view yet.

Thanks

        mFeedUpdatedSubscriber = event -> runOnUiThread(() -> setNotificationsCount(this, String.valueOf(event.getUnreadCardCount())));
        Appboy.getInstance(this).subscribeToFeedUpdates(mFeedUpdatedSubscriber);
        Appboy.getInstance(this).requestFeedRefresh();

**Comment by radixdev** [comment]
Hi @mohamedbrahem ,

Can you please update your issue with the [issue template](https://raw.githubusercontent.com/Appboy/appboy-android-sdk/master/.github/ISSUE_TEMPLATE.md)?
Can you also provide [verbose logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#verbose-logging) demonstrating the issue?

Thanks,
Julian

**Comment by radixdev** [comment]
Hey @mohamedbrahem ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
