### ISSUE TITLE
Manifest permission for firebase messaging

### ISSUE THREAD

**Issue by dhaksddj** [Appboy/appboy-android-sdk#112]
* [ ] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

**Comment by dhaksddj** [comment]
Can you clarify whether why the manifest has all the permissions that apparently are not needed?

In fact, the google sample has no permissions.

**Comment by radixdev** [comment]
Which permissions are you referring to? Can you link to the documentation/sample code to the permissions themselves?

Thanks,
Julian

**Comment by radixdev** [comment]
Hey @dhaksddj ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
