### ISSUE TITLE
appboybridge not ready on page load

### ISSUE THREAD

**Issue by sergiandreplace** [Appboy/appboy-android-sdk#113]
I'm creating an in-app campaign with html content. For campaign purposes, I need to log and event when the page is shown.

What I do is just add `appboyBridge.logCustomEvent("myEvent")` at the beginning of the code. But, unfortunately, this line crashes.

After investigation of source code, I've found that you inject the appboyBridge javascript via url once the page is loaded. Fine, but then, there is no way to be sure how to detect when appboyBridge is available.

A suggestion is to add an event to notify that the bridge is ready, for example:
```
window.dispatchEvent("appboyBridgeReady")
```
This will make possible to know when it's initialized via subscribe to this event.

Does this makes sense? :)

Thanks in advance

**Comment by radixdev** [comment]
Fantastic issue and solution. I've reproduced the issue and verified that your fix works (thanks!). In terms of a release estimate, we have to weigh how we approach this for the other platform SDKs for parity.

Another approach you could take here would be [adding an In-App Message Manager Listener](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/customization/#setting-a-custom-manager-listener) and logging your event in the `beforeInAppMessageDisplayed` method.

**Comment by sergiandreplace** [comment]
Great! I'll keep waiting ;)

Thanks for the workaround, but we try to avoid ad-hoc solutions for campaigns in code. Meanwhile, we are using a simple delay. Not the best approach, but it works.

Thanks for the quick answer!

**Comment by radixdev** [comment]
Hi @sergiandreplace ,

This is available in SDK version 3.1.0. The event name is `ab.BridgeReady`. Please let me know if this fixes your issue.

Julian

**Comment by radixdev** [comment]
Hey @sergiandreplace ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
