### ISSUE TITLE
Should not enforce waking up the screen when a notification is received

### ISSUE THREAD

**Issue by Sloy** [Appboy/appboy-android-sdk#115]
We received complaints from some users about our application turning on their phone screen when receiving a notification. Most notifications are less intrusive. For example, some devices just show an “ambient display” with a black background and dimmed screen.

This is not an option for notifications in Android, so after some (much) research we found that the issue was caused by Braze SDK, specifically the following line of code:
https://github.com/Appboy/appboy-android-sdk/blob/3aff87788f0f744ee101275b0b924a0284106f1a/android-sdk-ui/src/com/appboy/AppboyFcmReceiver.java#L110

In our opinion, this should be an opt-in behavior, most applications will want to respect how the system handles notifications. But if you prefer to make it the default behavior, providing at least a way to opt-out would be ideal.

I hope you can agree with us on this. Thanks!

**Comment by radixdev** [comment]
Hello @Sloy ,

This is now fixed in version 3.1.0 of the SDK. Please see the [changelog](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md) for information.

Cheers,
Braze Android Team

**Comment by Sloy** [comment]
You guys are awesome! Thanks a lot ❤️
