### ISSUE TITLE
In App Messaging crashing transparent/translucent activities

### ISSUE THREAD

**Issue by bnvinay92** [Appboy/appboy-android-sdk#116]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?

2.2.5

## What did you do?

Integrated Braze with the lifecycle listener and used automatic push registration.

## What did you expect to happen?

Not Crash.

## What happened instead?

The SDK causes the app to crash if an In-App-Message is received on a translucent activity. This is because this sdk is calling `setRequestedOrientation`, in the `resetAfterInAppMessageClose` method of `AppboyInAppMessageManager`, which is not supported with translucent/transparent activities on apps with `compileSdkVersion` >= 27

**Comment by radixdev** [comment]
I believe this was fixed in [version 2.5.1](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#251) of the SDK. Can you update to a recent SDK release and verify this is still an issue?

Thanks,
Julian
