### ISSUE TITLE
Class "com/amazon/device/messaging/ADM" not found on any classpath. Used by class "bo/app/bf"

### ISSUE THREAD

**Issue by prady32** [Appboy/appboy-android-sdk#120]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?

3.0.1

## What did you do?

I am trying to build my project I get the following error
Class "com/amazon/device/messaging/ADM" not found on any classpath. Used by class "bo/app/bf"

## What happened instead?

Class "com/amazon/device/messaging/ADM" not found on any classpath. Used by class "bo/app/bf"

## Steps to reproduce

Added this to gradle and trying to build compile "com.appboy:android-sdk-ui:3.0.1"

**Comment by Bucimis** [comment]
Hi @prady32 - that's unexpected behavior. What version of Android Studio and the Android Gradle plugin are you using? Also, is there anything unusual or custom about your build system?

**Comment by prady32** [comment]
Android Studio - 3.0.1
Gradle version: 4.3.1
Mine is Ninja Build system used by Chromium open source to build project.

**Comment by Bucimis** [comment]
@prady32 it looks like the build may be failing here https://github.com/chromium/chromium/blob/master/build/android/bytecode/java/org/chromium/bytecode/ClassPathValidator.java#L37. In some instances, the Braze SDK imports classes (e.g. `ADM` classes and `Google Play Services` classes) without requiring them to be in the path. We use reflection and take advantage of lazy class loading to ensure all usages are safe. 

Would it be possible to disable the classpath check on your end? It may also be possible to include the ADM jar just to get the build to pass, or stub out missing classes. If those approaches don't work, we may potentially need to make a bespoke build for you that removes all ADM imports.

**Comment by prady32** [comment]
Thanks for the reply @Bucimis. I added ADM jar it worked.
