### ISSUE TITLE
AppboyInAppMessageBoundedLayout Error: Attribute "android:maxWidth" has already been defined

### ISSUE THREAD

**Issue by saebinna** [Appboy/appboy-android-sdk#122]
AppboyInAppMessageBoundedLayout has attribute android:maxWidth. but android:maxWidth is already defined.. so i got error 'Attribute "android:maxWidth" has already been defined'
when i build the project.

**Comment by radixdev** [comment]
Hello @saebinna ,

Thanks for filing this issue. Unfortunately, declared styles are global and not namespaced to the `declare-styleable` name. We plan on providing a fix shortly.

Cheers,
Braze Android Team

**Comment by radixdev** [comment]
Hi @saebinna ,

This issue is resolved in SDK 3.2.1 which was just released. Let us know if this fixes your issue.

Julian
