### ISSUE TITLE
Text (with Optional Image) layout seems broken since 3.2.0

### ISSUE THREAD

**Issue by nelljohan** [Appboy/appboy-android-sdk#125]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

3.2.0 or 3.2.1

Environment:
- Android Q Beta 2
- Pixel 3 XL

## What did you do?

Integrate GIF support for In-App messages as per - https://www.braze.com/docs/developer_guide/platform_integration_guides/android/in-app_messaging/customization/#gifs-delegate-integration

## What did you expect to happen?

The image / GIF to render as expected on the message

## What happened instead?

With an image it seems stretched out (source image is the current aspect ratio as requested by the dashboard)

Text (with Optional Image)
![Screenshot 2019-04-09 at 11 57 25](https://user-images.githubusercontent.com/1705810/55791384-af216c00-5abe-11e9-97d6-f037a8e516fa.png)

Image Only
![Screenshot 2019-04-09 at 11 57 12](https://user-images.githubusercontent.com/1705810/55791382-adf03f00-5abe-11e9-9826-66dd3785dda4.png)

Source Image: 
![source](https://user-images.githubusercontent.com/1705810/55791481-ded07400-5abe-11e9-9e85-8cf612f138ab.png)

## Steps to reproduce

- Configure an in-app message campaign
- Make sure the Layout is set to `Text (with Optional Image)` (`Image Only` works as expected)
- Trigger the campaign on a device
- Downgrading to 3.1.1 fixes the issue and the message displays correctly again

**Comment by nelljohan** [comment]
Looks like this was fixed in 3.2.2 👍

**Comment by radixdev** [comment]
Hi @nelljohan ,

Sorry about that! This issue was reported internally and in addition this issue slipped my attention. This is indeed fixed in 3.2.2.
