### ISSUE TITLE
Support for long property values in AppboyProperties.addProperty

### ISSUE THREAD

**Issue by arnihermann** [Appboy/appboy-android-sdk#127]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Standard Reporting

## What version of the Braze Android SDK are you using?

Latest

## What did you do?

`props.addProperty("propName", variable)` where variable is of type `long`

## What did you expect to happen?

The code to compile.

## What happened instead?

Code does not compile.

## Steps to reproduce

`addProperty("propName", System.currentTimeMillis())`

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No.

## Project that demonstrates the issue

Does not apply.

# ANR Reporting

Does not apply.

## Entire ANR Report

Does not apply.

## Braze Related Threads In ANR

Does not apply.

**Comment by Bucimis** [comment]
Hi @arnihermann, our properties object accepts integers, doubles, booleans, `java.util.Date` objects, or strings. Longs aren't currently supported. To store a timestamp, we recommend using a `java.util.Date` object

**Comment by arnihermann** [comment]
@Bucimis are there plans to add support for long? I just used `System.currentTimeMillis()` as an example.

**Comment by Bucimis** [comment]
Thanks for the context @arnihermann - we'll add support in our next release.

**Comment by arnihermann** [comment]
@Bucimis Thanks, much appreciated :pray:

**Comment by radixdev** [comment]
Hi @arnihermann ,

This was released in SDK 3.3.0. Please let us know if this fixes your issue.

**Comment by radixdev** [comment]
Hey @arnihermann ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Comment by arnihermann** [comment]
@radixdev Thanks! I just updated the lib and my code compiles 🎉 Thanks for the quick response.
