### ISSUE TITLE
Full-screen In-App message does not match the screen height

### ISSUE THREAD

**Issue by tommybuonomo** [Appboy/appboy-android-sdk#128]
# Standard Reporting

## What version of the Braze Android SDK are you using?
3.2.1

## What did you do?
Test Full In-App Message on a OnePlus 6

## What did you expect to happen?
The fullscreen In-App Message fill the screen height

## What happened instead?
There is a margin on top of the In-App message:
![image](https://user-images.githubusercontent.com/15737675/57688942-e1366880-763e-11e9-940a-8ae1e0f17146.png)

## Steps to reproduce
Test an In-App message on a OnePlus6

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
No

**Comment by radixdev** [comment]
Hello @tommybuonomo ,

We're very actively tracking this issue. The root cause appears to be related to the device having a notch and also running on Android Oreo. Android Pie added official notch APIs and we don't have retroactive ways of detecting a notch before that API became available. We will update you on any progress we make here.

**Comment by tommybuonomo** [comment]
Hello @radixdev ,

Thanks for the quick answer. Note that the OnePlus I used is on Android Pie and not Android Oreo.
Keep me in touch if there is any way for us to bypass this, like a style attribute or a class override.

**Comment by radixdev** [comment]
That logic is in `InAppMessageViewWrapper`, which cannot be overridden. The Android Pie information is extremely good to know. We've purchased a OnePlus for debugging and should have another update for you soon.

**Comment by radixdev** [comment]
Update. It's fixed in 3.3.0 ;)

Please let us know if this solves your issue!

**Comment by radixdev** [comment]
Hey @tommybuonomo ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.

**Comment by tommybuonomo** [comment]
Hi @radixdev,

Yes it's fixed on `3.3.0`. 

Thanks for your reactivity.
