### ISSUE TITLE
Full-screen In-App message close button tappable area is too small

### ISSUE THREAD

**Issue by jakob-bird** [Appboy/appboy-android-sdk#129]
# Standard Reporting

## What version of the Braze Android SDK are you using?

3.2.1

## What did you do?

Test Full In-App Message

## What did you expect to happen?

X button would be of a tappable size according to Google's accessibility standards, something around 48x48dp.

## What happened instead?

The X button is 15x15 dp, very easy to miss and accidentally interact with the Full In-App Message instead.

## Steps to reproduce

Test an In-App message.

**Comment by radixdev** [comment]
Hello @jakob-bird ,

Please see [AppboyInAppMessageImmersiveBaseView](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/appboy/ui/inappmessage/views/AppboyInAppMessageImmersiveBaseView.java#L96-L131) where we enlarge the close buttons on full/modal in-app messages to 40dp x 40dp. If you would like an even larger click target, you can override [the style](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/res/values/styles.xml#L167-L176).

**Comment by radixdev** [comment]
Hey @jakob-bird ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
