### ISSUE TITLE
IInAppMessage is not accessible in the ButtonClickListener

### ISSUE THREAD

**Issue by neugartf** [Appboy/appboy-android-sdk#130]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

3.2.1

## What did you do?
Using the button click listener [1], I wanted to implement different behavior based on the campaign when the user clicks on a button in an in app message delivered by braze.

[1] https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/ui/inappmessage/listeners/AppboyDefaultInAppMessageManagerListener.html#onInAppMessageButtonClicked-com.appboy.models.MessageButton-com.appboy.ui.inappmessage.InAppMessageCloser-

## What did you expect to happen? / What happened instead?
`public boolean onInAppMessageButtonClicked(MessageButton button,
                                           InAppMessageCloser inAppMessageCloser)` should allow access to the InAppMessage, unfortunately you can't access this since the wrapper is made private. It is possible to do in iOS.

**Comment by radixdev** [comment]
Hi @neugartf ,

This should be trivial to implement. You can expect it in the next release.

Thanks,
Julian

**Comment by neugartf** [comment]
Thanks! Looking forward to it!

**Comment by radixdev** [comment]
This is released/now possible in SDK 3.4.0. Enjoy!

**Comment by neugartf** [comment]
Thanks :)
