### ISSUE TITLE
push notification is not displayed (android integration)

### ISSUE THREAD

**Issue by shuzootani** [Appboy/appboy-android-sdk#131]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) 

## What did you do?
I followed the docs to integrate push notification into react-native app which has already FCM setup, sent a test push from console but it's not displayed on android device although it says "successfully sent" on console.

<img width="630" alt="Screen Shot 2019-06-18 at 14 14 14" src="https://user-images.githubusercontent.com/19385183/59836795-7a4a5480-934c-11e9-865c-d0b71bd2b462.png">

I also tested inAppMessage and it works.

my codebase changes are like

- modified:   android/app/build.gradle
- new file:   android/app/src/dev/res/values/appboy.xml
- modified:   android/app/src/main/AndroidManifest.xml
- modified:   android/app/src/main/java/com/packageName/MainApplication.java
- new file:   android/app/src/main/res/values/appboy.xml
- modified:   android/build.gradle
- modified:   android/settings.gradle
- modified:   package.json

build.gradle

``` gradle
+ implementation "com.appboy:android-sdk-ui:3.3.0"
```

AndroidManifest.xml

``` xml
        // I already had FCM installed before, which I'm not sure if I should remove.
        <service android:name="io.invertase.firebase.messaging.RNFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name="io.invertase.firebase.messaging.RNFirebaseInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
   
        // this is what I added.
        <service android:name="com.appboy.AppboyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
```

MyApplication.java

``` java
      AppboyConfig appboyConfig = new AppboyConfig.Builder()
        .setDefaultNotificationChannelName("defaultChannelName")
        .setIsFirebaseCloudMessagingRegistrationEnabled(true)
        .setFirebaseCloudMessagingSenderIdKey("fcm_sender_id")
        .setPushDeepLinkBackStackActivityEnabled(true)
        .setPushDeepLinkBackStackActivityClass(MainActivity.class)
        .setHandlePushDeepLinksAutomatically(true)
        .build();
      Appboy.configure(this, appboyConfig);
      registerActivityLifecycleCallbacks(new AppboyLifecycleCallbackListener(true, true));
```

## What happened instead?
I got an error `"Received 'Error: DEVICE_UNREGISTERED"` in Message Activity Log tab.

I'd appreciate if anyone could tell me what I'm missing or doing wrong.
Let me know if you need any further info.
Thanks.

**Comment by radixdev** [comment]
1. Does your sender ID match that of the one in the dashboard?
2. If you're already using a Firebase Messaging Service, you should follow https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#using-your-own-firebase-messaging-service instead of adding our Firebase Messaging Service.


Getting verbose logs would really help here.
1. Enable verbose logging from our SDK https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#verbose-logging
2. Force close the app
3. Start the app
4. Send a push from the dashboard
5. Send all of the logs starting from step 1.

If those logs above contain sensitive info you'd not want to post here, I'd recommend emailing support@braze.com.

**Comment by shuzootani** [comment]
Thanks @radixdev 
I'm able to make it work on ios but I think I'm facing the following issue on android.
https://github.com/invertase/react-native-firebase/issues/1129

I'm already using `react-native-firebase` for handling push notification messages.
so I probably have to make a custom service file to put `AppboyFirebaseMessagingService` and `RNFirebaseMessagingService` together.

I'm not familiar with Java and android project, so I'd really appreciate if you could show me some guidelines about how to do it properly.

**Comment by Bucimis** [comment]
@shuzootani 

1) create a Java class that extends `FirebaseMessagingService` (you can probably just use `RNFirebaseMessagingService`)
2) in `onMessageReceived(RemoteMessage remoteMessage)`, if the `remoteMessage` came from Braze as determined by `AppboyFirebaseMessagingService.isBrazePushNotification()`, pass it into `AppboyFirebaseMessagingService.handleBrazeRemoteMessage()`.
3) For non-Braze `remoteMessage` objects, do your usual handling

**Comment by shuzootani** [comment]
Thank you @Bucimis !!
Now it works 🎉 

I just made a class that extends `RNFirebaseMessagingService`
so now I have just one `<service />` tag for custom class that handles messages in `AppManifest.xml` instead of `AppboyFirebaseMessagingService`.

AppManifest.xml
``` AppManifest.xml
<service android:name="com.xxx.CustomMessagingService">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```

CustomMessagingService.java
``` java
import io.invertase.firebase.messaging.RNFirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;
import com.appboy.AppboyFirebaseMessagingService;

public class CustomMessagingService extends RNFirebaseMessagingService {
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);
        if (AppboyFirebaseMessagingService.handleBrazeRemoteMessage(this, remoteMessage)) {
            // This Remote Message originated from Braze and a push notification was displayed.
            // No further action is needed.
        } else {
            // This Remote Message did not originate from Braze.
            // No action was taken and you can safely pass this Remote Message to other handlers.
        }
  }
}
```

**Comment by Bucimis** [comment]
@shuzootani いいですね!

**Comment by bernardorubin** [comment]
@shuzootani This will make the data tracking for opened messages on android no longer trackable, correct?
