### ISSUE TITLE
Android AppBoy initialization best practices

### ISSUE THREAD

**Issue by Elvis10ten** [Appboy/appboy-android-sdk#132]
Hello,

How do we know when a call to set the user information succeeds or fails? Or how do we check if these values have been saved so we don't have to set them again.

Because AppboyUser asynchronously saves to SharedPreferences, there is a small chance that saving to SharedPreferences can fail before the values are sent to Braze servers?

Currently, we set these values on every app launch, but we want to move away from that and only fetch the user information only when required.

Thanks.

**Comment by radixdev** [comment]
Hi @Elvis10ten ,

1. Methods on the [`AppboyUser`](https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/AppboyUser.html#setCustomUserAttribute-java.lang.String-java.lang.String-) object return a boolean flag indicating success or failure. Events would only not be saved if they failed validation as specified in the javadoc (i.e. some value is too long).
2. We have extensive error monitoring in place that would report a `SharedPreferences` failure so I wouldn't be concerned with a small chance of SharedPreferences failing to write. Those writes are first written to memory so there'd have to be 2 levels of failure for that to occur.
3. Setting user values on every launch would result in that data getting sent repeatedly. I would also recommend only providing that data when required/first available.

**Comment by radixdev** [comment]
Hey @Elvis10ten ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
