### ISSUE TITLE
ClassCastException in com.appboy.models.InAppMessageHtmlFull when sending custom In-App Message

### ISSUE THREAD

**Issue by pragyagrawal** [Appboy/appboy-android-sdk#134]
Hi All,

We recently upgraded our client from V3.0.1 to v3.5.0 version, while testing the upgrade we found an error with custom in app message. 

Here is stack trace 
```

E/Appboy v3.5.0 .com.appboy.ui.inappmessage.AppboyInAppMessageManager: Could not display in-app message with payload: {
      "message": “Place_holder”,
      "type": "HTML_FULL",
      "message_close": "SWIPE"
    }
    java.lang.ClassCastException: com.appboy.models.InAppMessageHtmlFull cannot be cast to com.appboy.models.InAppMessageImmersiveBase
        at com.appboy.ui.inappmessage.AppboyInAppMessageManager.displayInAppMessage(AppboyInAppMessageManager.java:533)
        at com.appboy.ui.inappmessage.AppboyAsyncInAppMessageDisplayer$1.run(AppboyAsyncInAppMessageDisplayer.java:71)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

While going through the code, I found that this issue starts happening from v3.2.0 onwards. Comparing the tags and going through the file diff: https://github.com/Appboy/appboy-android-sdk/compare/v3.0.0...v3.2.0

I found that this line was introduced 
```
InAppMessageImmersiveBase inAppMessageImmersiveBase = (InAppMessageImmersiveBase) inAppMessage;
```
But if you look at the code, we are checking instance of view not message`if (inAppMessageView instanceof IInAppMessageImmersiveView) {` but later typecasting the message into InAppMessageImmersiveBase. 

This typecasting was added to support a new api `inAppMessageViewImmersive.getMessageButtonViews(numButtons)` which now need number of buttons. 

* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Standard Reporting

## What version of the Braze Android SDK are you using?

V 3.5.0

## What did you do?
Trying to test Custom in-app message to display in app message inside the app. Sent a test in-app message from the console. 

## What did you expect to happen?
In App Message displays correctly inside the app. 

## What happened instead?
No In App message displays inside the app, Braze throws an error on LogCat with the exception trace.

## Steps to reproduce
- Use the latest braze SDK with 3.5.0 and in app messaging enabled. 
- Sent a custom in app message from the braze console. 
- You should get a push notification, open the app and the message would not be displayed. 
- Look at logcat for the error.

**Comment by radixdev** [comment]
1. Can you provide details on the customizations you've done?
2. Can you provide the complete [verbose logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/additional_customization_and_configuration/#verbose-logging) starting from a cold start of the app and ending some time after you get the error?
3. Can you provide the full source of the "custom in-app message" view you're using?
4. What's the campaign type you're using on the dashboard to create this "custom in-app message"? An HTML in-app message, slideup, etc. Can you link to the campaign?
5. Does your in-app message contain buttons?

Also a reminder that if any of the above information is private/cannot be shared here, please feel free to email support@braze.com instead.

**Comment by radixdev** [comment]
Hey @pragyagrawal ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
