### ISSUE TITLE
Can't use existing color resource as notification accent color

### ISSUE THREAD

**Issue by GrahamBorland** [Appboy/appboy-android-sdk#135]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

3.5.0

## What did you do?

Tried to add definition for `com_appboy_default_notification_accent_color` using an existing color resource.

## What did you expect to happen?

I should be able to set `com_appboy_default_notification_accent_color` to an existing color resource. Something like this:
```xml
<color name="com_appboy_default_notification_accent_color">@color/my_accent_color</color>
```

## What happened instead?

I can only pass in a fully-resolved `#aarrggbb` integer value for `com_appboy_default_notification_accent_color`.

## Steps to reproduce

1. Create `appboy.xml`
2. Add entry for  `com_appboy_default_notification_accent_color` as per the documentation.
```xml
<integer name="com_appboy_default_notification_accent_color"></integer>
```
3. Observe that you can only supply an integer value, not a color resource.

It is in principle possible to do this in code
```kotlin
.setDefaultNotificationAccentColor(ContextCompat.getColor(context, R.color.my_accent_color))	
```
but for other reasons (mParticle SDK integration) we're unable to configure this at runtime and have to use the `appboy.xml` static config.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

N/A

**Comment by radixdev** [comment]
Hi @GrahamBorland ,

We have this implemented and it should be available in the next release. Thank you for your patience here.

**Comment by radixdev** [comment]
Hi @GrahamBorland ,

Thanks for filing this issue. This is added in 3.8.0. Please see the [changelog](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md) for information.

Cheers,
Julian

**Comment by GrahamBorland** [comment]
@radixdev Fabulous, thank you. 😄
