### ISSUE TITLE
Extras are not writable in IInAppMessage

### ISSUE THREAD

**Issue by neugartf** [Appboy/appboy-android-sdk#136]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

3.2.1

## What did you do?
We are trying to add `extras` [1] to an `IInAppMessage` on the device during run time, which unfortunately doesn't provide a setter. 
[1] https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/IInAppMessage.html#getExtras--

## What did you expect to happen? / What happened instead?
Android should allow write access to the `extras` field the same way as the iOS SDK does in order to have both SDKs aligned [1]
[1] https://appboy.github.io/appboy-ios-sdk/docs/interface_a_b_k_in_app_message.html#a0f733a940506e7be04c3c6503c87f4db

**Comment by radixdev** [comment]
Hi @neugartf,

We've added this to our roadmap, should be trivial to implement.

**Comment by radixdev** [comment]
This was released in 3.7.1 of the SDK
