### ISSUE TITLE
Unable to show image with rounded corners in content cards

### ISSUE THREAD

**Issue by vicpinm** [Appboy/appboy-android-sdk#137]
## What version of the Braze Android SDK are you using?
3.6.0

## What did you do?
Sending content cards campaigns with banners and captioned images. 

## What did you expect to happen?
For banners, I want to show the image with all corners rounded. For captioned images, I just want to show top rounded corners. 

## What happened instead?
I get no rounded corners images:

![]( https://cl.ly/d45815a3e63e/Captura%252520de%252520pantalla%2525202019-09-12%252520a%252520las%25252016.21.36.png)

I could use ```IAppboyImageLoader``` to round image corners, but I cannot differentiate the type of card the image is for, to decide whether round all corners or just the top ones. 

Not sure if this is possible currently somehow. If not, it would be super useful to have more information about the card the image is for in the ```IAppboyImageLoader```  class.

**Comment by vicpinm** [comment]
Hi @radixdev , if I use that method to overriding the default onBindViewHolder behaviour then I would have to do all the binding manually, and that is want I'm trying to avoid.

**Comment by radixdev** [comment]
Fair point. If `IAppboyImageLoader.renderUrlIntoView` had a sister method, something like `IAppboyImageLoader.renderUrlIntoContentCardView`, and that method took a `Card` instance as a parameter, would that accomplish what you're looking for?

**Comment by vicpinm** [comment]
Yes, that is the parameter I'm missing, a card instance to get its type in that callback, but it seems is not there anymore: 

![](https://cl.ly/58c3c56cba67/Captura%252520de%252520pantalla%2525202019-09-16%252520a%252520las%25252012.53.45.png)

**Comment by radixdev** [comment]
Ok, that should be fairly easy to do. I'll update this issue with any progress

**Comment by vicpinm** [comment]
Thanks a lot @radixdev !!

**Comment by radixdev** [comment]
Hi @vicpinm , 

This is currently in QA and should be in the next release.

**Comment by radixdev** [comment]
Hey @vicpinm ,

Please see the 3.8.0 changelog. The `IAppboyImageLoader` interface was revamped and should allow for what you need. Specifically see [this method](https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/IAppboyImageLoader.html#renderUrlIntoCardView-android.content.Context-com.appboy.models.cards.Card-java.lang.String-android.widget.ImageView-com.appboy.enums.AppboyViewBounds-).

Let me know if this fixes your issue.
