### ISSUE TITLE
 Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jchristof** [Appboy/appboy-android-sdk#143]
Firebase reported Appboy crash:

com.appboy.ui.contentcards.AppboyCardAdapter.isItemDismissable (AppboyCardAdapter.java:80)
com.appboy.ui.contentcards.recycler.SimpleItemTouchHelperCallback.getMovementFlags (SimpleItemTouchHelperCallback.java:28)

**Comment by radixdev** [comment]
Hey @jchristof ,

Please fill out the issue template. Items such as SDK version and reproduction steps are missing from your issue.

**Comment by jchristof** [comment]
Sorry, I don't have repro steps yet. We consume the library via an Mparticle kit. Mparticle version 5.10.3

**Comment by radixdev** [comment]
Hello @jchristof ,

Thanks for filing this issue. Can you try updating the Braze SDK dependency to 3.8.0 and seeing if the issue persists? We addressed a Content Cards issue in that release that seems similar. Please see the [changelog](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md) for information.

Cheers,
Braze Android Team
