### ISSUE TITLE
AppboyWebViewActivity crashes on tablet running 6.0.1

### ISSUE THREAD

**Issue by jtellezvs** [Appboy/appboy-android-sdk#144]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
3.7.0

## What did you do?
Integrated Braze content cards, and while opening webviews work fine on a phone, tablets crash consistently.

## What did you expect to happen?
Opening a webview on tablet will not crash the app and display the correct web page

## What happened instead?
After clicking a content card, the app crashes.

## Steps to reproduce
- Start the app
- Open content card screen
- Click content card with web link
- App crashes

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
No custom code aside from modifying the layout of the cards. I did however try to add the web activity to the manifest as described in a different issue from 2016, but that also did not solve the issue.

## Project that demonstrates the issue
No project to look at, but this is the stack trace I see

`Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{com.vividseats.android.stage/com.appboy.ui.AppboyWebViewActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content`

# ANR Reporting

**Comment by radixdev** [comment]
Hi @jtellezvs ,

Please update your SDK to [3.7.1](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#fixed-1) or higher and report back if you still experience this issue.

**Comment by jtellezvs** [comment]
Thanks, the suggestion addresses this issue.
