### ISSUE TITLE
The push notifications large image is not displayed properly

### ISSUE THREAD

**Issue by kateLebedevaDDI** [Appboy/appboy-android-sdk#145]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
4.0.0

## What did you do?

I've used the method from the documentation in appboy.xml file and put the resource to display there
`<drawable name="com_appboy_push_large_notification_icon">@drawable/ic_stat_notify_droidboy_large</drawable>`

## What did you expect to happen?

The image should be shown as a large icon in the push notification

## What happened instead?

The image was not shown as large icon but the gray background was there instead

## Steps to reproduce

- add the following code to the appboy.xml
`<drawable name="com_appboy_push_large_notification_icon">@drawable/ic_stat_notify_droidboy_large</drawable>` 
or add the icon from the resource code
` String iconName = getResources().getResourceEntryName(R.drawable.ic_stat_notify_droidboy_large);
        AppboyConfig appboyConfig = new AppboyConfig.Builder()
                .setLargeNotificationIcon(iconName)
                .build();
        Appboy.configure(this, appboyConfig);
`
- Start the app
- Send test push notification from firebase
- Open the notification on the device
- The large notification image is not displayed - only the default gray images background is shown

**Comment by Bucimis** [comment]
@kateLebedevaDDI Thanks for reporting - a few thoughts:
1) You should ensure the name of your icon specified in `appboy.xml` contains the `@drawable` prefix, is spelled correctly, and refers to a drawable resource in your app file (just as a sanity check, note that the provided example points to an image in our Droidboy sample app which is not part of the SDK).
2) Braze will only apply push icon settings when push is sent through the Braze dashboard or API, or sent through a third party but displayed by the Braze SDK. Push sent through the Firebase dashboard and displayed by the Firebase SDK won't use Braze push icon settings.

**Comment by kateLebedevaDDI** [comment]
@Appboy
Thanks for help
But the icon specified in appboy.xml is right - the name is spelled correctly and it is in the app/res/drawable file
also I tried to send the message from Braze's dashboard as you advised but added those drawables  into appboy.xml before
   ```
 <drawable name="com_appboy_push_small_notification_icon">@drawable/ic_launcher_foreground</drawable>
    <drawable name="com_appboy_push_large_notification_icon">@drawable/ic_launcher_foreground</drawable>
```
and I got this in the result
![photo_2019-11-26_15-30-28](https://user-images.githubusercontent.com/58161335/69637685-d59e1280-1061-11ea-97d9-543224c35632.jpg)
![photo_2019-11-26_15-30-33](https://user-images.githubusercontent.com/58161335/69637696-d8006c80-1061-11ea-86c7-4b4305f68b88.jpg)

**Comment by radixdev** [comment]
@kateLebedevaDDI 
1. Can you paste both assets here?
2. Have you read the notification guidelines in https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#step-2-configure-notification-icons ?

**Comment by kateLebedevaDDI** [comment]
@radixdev 
1) Yes, here it is:
![ic_launcher_foreground](https://user-images.githubusercontent.com/58161335/69707851-29ad0380-1103-11ea-9506-ebfde20bed0a.png)
2) Yes I've read the notification guidelines from the link you provided and from
here: https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/android/push_notifications/#step-3-configure-your-appboyxml

**Comment by radixdev** [comment]
Hi @kateLebedevaDDI ,

From the docs, your icon must be all white on a transparent background. I'd recommend removing the orange color from your icon and trying again. As your screenshot suggests, the icon looks suboptimal when displayed by the Android system due to how the notification area renders icons.

**Comment by Bucimis** [comment]
@kateLebedevaDDI note that the "small" notification icon should be transparent. The "large" notification icon may have color, i.e. you can continue to use your existing icon

**Comment by radixdev** [comment]
Hey @kateLebedevaDDI ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
