### ISSUE TITLE
SDK is crashing

### ISSUE THREAD

**Issue by samy-baili** [Appboy/appboy-android-sdk#146]
I'm using `com.appboy:android-sdk-ui:3.7.0`

![Screen Shot 2019-11-25 at 1 23 53 PM](https://user-images.githubusercontent.com/11545612/69532480-f8a7c400-0f86-11ea-8188-b416c294f2a4.png)

**Comment by radixdev** [comment]
Hi @samy-baili ,

Apologies, I missed seeing this issue due to the holidays. Please update to the latest SDK version (3.8.0 or 4.0.0). This issue has been addressed/resolved.

**Comment by radixdev** [comment]
Hey @samy-baili ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
