### ISSUE TITLE
Drop in reachable users after migrating to new project.

### ISSUE THREAD

**Issue by Hamdaaa91** [Appboy/appboy-android-sdk#149]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
4.0.2

## What did you do?
Migrate to new firebase project
1- set the new server key and sender id in braze.
2- set the new google.json in android project
3- update the appboy.xml file
4- in main activity i register braze useing this code
` val appboyConfig = AppboyConfig.Builder()
            .setIsFirebaseCloudMessagingRegistrationEnabled(true)
            .setFirebaseCloudMessagingSenderIdKey(FIREBASE_SENDER_ID)
            .build()
    Appboy.configure(context, appboyConfig)`

## What did you expect to happen?
I expected that the old users when they update the app, will still be reachable

## What happened instead?
I lost more than 80% present of reachable users on android.
Only new installs are reachable. 
Users already updated to the new version

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <bool translatable="false" name="com_appboy_firebase_cloud_messaging_registration_enabled">true</bool>
    <string translatable="false" name="com_appboy_firebase_cloud_messaging_sender_id">SENDER-ID/string>
    <string name="com_appboy_api_key">APPBOY KEY/string>
    <drawable name="com_appboy_push_small_notification_icon">@drawable/notification_icon</drawable>
    <drawable name="com_appboy_push_large_notification_icon">@mipmap/ic_launcher</drawable>
    <integer name="com_appboy_default_notification_accent_color">0xFFfcd755</integer>

    <bool name="com_appboy_handle_push_deep_links_automatically">false</bool>
    <bool name="com_appboy_push_deep_link_back_stack_activity_enabled">true</bool>
    <string name="com_appboy_push_deep_link_back_stack_activity_class_name">MAINACTIVITY</string>

    <integer name="com_appboy_session_timeout">1800</integer>
    <bool name="com_appboy_newsfeed_unread_visual_indicator_on">true</bool>
    <bool name="com_appboy_enable_fresco_library_use">true</bool>
</resources>
```
## Project that demonstrates the issue

# ANR Reporting

**Comment by radixdev** [comment]
Hi @Hamdaaa91 ,

I would highly recommend emailing support@braze.com for a more thorough investigation (such as viewing logs, examining user profiles, etc.). However, I can say that changing both the server key and sender ID will result in tokens for users on your old app to become invalid and bounce since they don't correlate with the new keys.

**Comment by Hamdaaa91** [comment]
Hi @radixdev 
I Contacted the braze support but unfortunately, the methods they recommended didn't work but caused more lose in our reachable users around 5k
I want to know if there's a way to force a token register through braze SDK

**Comment by Bucimis** [comment]
Hi @Hamdaaa91, it will require an app update, but you can request a push token manually in your app through the Firebase API and use https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/Appboy.html#registerAppboyPushMessages-java.lang.String- method to pass the push token to the SDK directly. This method is compatible with automatic Braze-FCM registration as long as the credentials used to get the push token are the same.

**Comment by radixdev** [comment]
Hey @Hamdaaa91 ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
