### ISSUE TITLE
Future releases?

### ISSUE THREAD

**Issue by fmedlin** [Appboy/appboy-android-sdk#151]
Is there an effort to bump to support later versions of appboy-android-sdk? Need any help? Just curious because I didn't see any timeline or milestones here. Thanks!

**Comment by radixdev** [comment]
Hi @fmedlin ,

Our release roadmap and progress tracking are all internal. But rest assured that we will continue to update this repository with exciting new features and support ;). Please see our [releases page](https://github.com/Appboy/appboy-android-sdk/releases) and star this repo for update notifications.

Have a great day!
Julian

**Comment by fmedlin** [comment]
Sorry, meant to ask this in android-segment-appboy. Hope the answer is the same! 😁
