### ISSUE TITLE
Connection Timeout from https://appboy.github.io/appboy-android-sdk

### ISSUE THREAD

**Issue by GermanMontejo** [Appboy/appboy-android-sdk#153]
Hi guys. We're getting connection timeouts from https://appboy.github.io/appboy-android-sdk
Caused by: org.gradle.internal.resource.transport.http.HttpRequestException: Could not GET 'https://appboy.github.io/appboy-android-sdk/sdk/com/google/firebase/firebase-analytics/maven-metadata.xml'. What's happening?

**Comment by GermanMontejo** [comment]
@Bucimis @radixdev thoughts?

**Comment by radixdev** [comment]
Please share your complete Gradle file so we can reproduce. Your app.gradle and build.gradle

**Comment by GermanMontejo** [comment]
Hi. For confidentiality reasons, I can't share our gradle files. But basically, our app was working last week and no gradle configuration changes has been made. We have this in our gradle file, just as stated in your ReadMe:

repositories {
   maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
   ...
}
The problem happens when gradle attempts to retrieve the firebase maven-metadata.xml file. If you click on that link I specified above, it will actually tell us: File Not Found.

**Comment by GermanMontejo** [comment]
Even if I just try to open the appboy.github.io url in the browser, it would show me a 404 page.

**Comment by GermanMontejo** [comment]
![Uploading Screenshot_20200302-205803.png…]()
Here's a screenshot.

**Comment by radixdev** [comment]
That's a Google firebase dependency and should not be resolved in our Maven repository. Can you point us to the braze pom file with that dependency or otherwise a way to reproduce? I understand if you cannot share the entire Gradle file, but a small reproducible Gradle would also help

**Comment by GermanMontejo** [comment]
I don't understand the part about it being a firebase dependency and should not be resolved in your maven repository. Even just going to appboy.github.io already shows us a 404.

**Comment by GermanMontejo** [comment]
Basically appboy.github.io does not exist on our side and we can't access it.

**Comment by Bucimis** [comment]
@GermanMontejo what do you see when you open https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/ or https://appboy.github.io/appboy-android-sdk/sdk/ in a browser? We definitely don't host a file with the path `com/google/firebase/firebase-analytics/maven-metadata.xml` which you should be able to verify by navigating the file explorer within the linked pages

**Comment by GermanMontejo** [comment]
Hi! Now I can see the directory listing. Yesterday it was just giving us 404. Glad that it's now up and running. I've posted a screenshot in my comment above showing you a 404 when I accessed appboy.github.io from my smartphone. Let me check later when I get to the office if the gradle error is still there about the unresolved maven metadata xml file.

**Comment by Bucimis** [comment]
@GermanMontejo thanks, that sounds good

**Comment by GermanMontejo** [comment]
@Bucimis failing to access https://appboy.github.io/appboy-android-sdk/sdk/ was prolly a firewall issue on our side. But it's weird that gradle is telling us that it can't find the file: com/google/firebase/firebase-analytics/maven-metadata.xml. I mean yes it can't because it doesn't exist in your repo but why is it trying to find it in appboy? I'll try to settle the firewall issue first before I proceed with the missing maven-metadata.xml file.

**Comment by GermanMontejo** [comment]
Hi. It turned out to be a firewall issue and we can now access the repo. Thanks for your help. 🙂
