### ISSUE TITLE
Error occured while executing Brazerequest: Android

### ISSUE THREAD

**Issue by bhargavis** [Appboy/appboy-android-sdk#157]
I'm facing the following error while registering with Braze in Android app

D/Appboy v7.0.0 .bo.app.j: Request(id = ec13ce2f5a572640) Executed in [9ms] [POST:https://https://rest.iad-03.braze.com/api/v3/data]
D/Appboy v7.0.0 .bo.app.dc: Experienced network communication exception processing API response. Sending network error event. Could not set up connection [https://https://rest.iad-03.braze.com/api/v3/data] [Unable to resolve host "https": No address associated with hostname].  Braze will try to reconnect periodically.
D/Appboy v7.0.0 .bo.app.ab: bo.app.af fired: bo.app.af@410bdc9
D/Appboy v7.0.0 .bo.app.ab: Triggering bo.app.af on 1 subscribers.
D/Appboy v7.0.0 .bo.app.q: Received network error event. Backing off.
D/Appboy v7.0.0 .bo.app.dp: Computing new sleep delay. Previous sleep delay: 92275
    New sleep duration: 246764 ms. Default sleep duration: 10000 ms. Max sleep: 300000 ms.
D/Appboy v7.0.0 .bo.app.q: Posting new sync runnable with delay 256764 ms
W/Appboy v7.0.0 .bo.app.dc: Experienced exception processing API response. Failing task.
E/Appboy v7.0.0 .bo.app.db: Error occurred while executing Braze request: An error occurred during request processing, resulting in no valid response being received. Check the error log for more details.
D/Appboy v7.0.0 .bo.app.ab: bo.app.ad fired: bo.app.ad@76a3cce
    Triggering bo.app.ad on 1 subscribers.
V/Appboy v7.0.0 .bo.app.dq: Notifying confirmAndUnlock listeners for cache: bo.app.du@25c3a21
V/Appboy v7.0.0 .bo.app.dq: Notifying confirmAndUnlock listeners for cache: bo.app.eg@180fe46

**Comment by Bucimis** [comment]
Hi @bhargavis, `https://` appears twice in `https://https://rest.iad-03.braze.com/api/v3/data`. When you configure your endpoint, you can omit `https://` (in your case, you would set the endpoint to `rest.iad-03.braze.com`).

**Comment by radixdev** [comment]
Hey @bhargavis ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
