### ISSUE TITLE
Update to Firebase Messaging v20.x.x 

### ISSUE THREAD

**Issue by weverb2** [Appboy/appboy-android-sdk#159]
* [X] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

8.0.1

## What did you do?

I installed braze alongside other firebase dependencies (firebase remote config in this case)

## What did you expect to happen?

The app to start normally on fresh install

## What happened instead?
The app crashed on fresh install with the following message:
```
java.lang.IllegalAccessError: Illegal class access: 'com.google.firebase.messaging.zzc' attempting to access 'com.google.firebase.iid.zzaz' (declaration of 'com.google.firebase.messaging.zzc' appears in /data/app/my.package.name-2STqrRB28R0JJghO_GWxJQ==/base.apk!classes2.dex)
        at com.google.firebase.messaging.zzc.onBind(com.google.firebase:firebase-messaging@@20.1.0:11)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3980)
        at android.app.ActivityThread.access$1600(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1880)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
## Steps to reproduce

Follow steps to integrate braze with firebase messaging, install other firebase component (firebase remote config for example)

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

no

**Comment by radixdev** [comment]
Can you provide the exact versions of all other firebase dependencies used to reproduce?

**Comment by weverb2** [comment]
Should be able to reproduce with these:

 "com.google.firebase:firebase-core:17.2.2"
 "com.google.firebase:firebase-messaging:20.1.0"
 "com.google.firebase:firebase-config-ktx:19.1.4"

**Comment by radixdev** [comment]
This is an AndroidX app? Can you also post the exact Braze SDK dependency as well (i.e. are you using the jetified artifact)?

**Comment by weverb2** [comment]
Yes this is an AndroidX app.

I started seeing the error using com.appboy:android-sdk-ui-x:4.0.2
But then saw that it was several versions behind.

Updated to com.appboy:android-sdk-ui-jetified:8.0.1 and still saw the issue.  (different issue, but it is hard to find documentation that you are supposed to be using this dependency in the first place, it is only listed in a changelog, I'd expect to find it in a readme)

**Comment by radixdev** [comment]
1. I made an example jetified/kotlin project in https://github.com/radixdev/android-public-issue-159 and couldn't reproduce with your steps. The app does not crash and a FCM token is retrieved.
2. The SDK doesn't actually have a hard dependency on any firebase version (see [the POM](https://github.com/Appboy/appboy-android-sdk/blob/gh-pages/sdk/com/appboy/android-sdk-ui-jetified/8.0.1/android-sdk-ui-jetified-8.0.1.pom)). We invoke the firebase registration logic via the following code `FirebaseInstanceId.getInstance().getToken(firebaseSenderId, FIREBASE_INSTANCE_SCOPE)` and have a compileOnly dependency.
3. Duly noted. I've added a story to add the proper jetification docs to our full documentation so you won't have to hunt for it.

**Comment by weverb2** [comment]
Thanks for looking into this.  I'll see if I can't get it to work somehow. I do notice in your example project that you aren't depending on firebase-core or firebase-analytics.  That is something that is in my app that I listed above.

Before adding remote-config to my project, I updated the core dependency to just analytics (as recommended in the Firebase docs) but I believe both were giving me issues.

**Comment by weverb2** [comment]
I think I found the issue!

I update my own dependency of firebase-cloud-messaging to 20.2.0 and the crash on fresh install seems to have gone away. 

Looking at their release notes for the version it seems to track:
> Internal changes to ensure functionality alignment with other SDK releases

Thanks for digging into this. Sorry for the runaround.

**Comment by radixdev** [comment]
Unrelated, those androidX jetified docs should be live in a week or so. Thanks again for that note
