### ISSUE TITLE
Handle open deeplink on foreground 

### ISSUE THREAD

**Issue by laitr01** [Appboy/appboy-android-sdk#160]
I have a problem when open deeplink from push notification like below:
My application have three activities.
SplashActivity -> MainActivity -> ChatActivity

I choose the splash screen to handle deeplink to a specific screen, so i set `singleTask` launch mode and  for it.
```
         <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data android:scheme="app" />
            </intent-filter>
```

- When the app was killed or running in background, i think everything works well.
- When the app is on foreground, assumption i am stand at MainActivty and i click on push notification contains deeplink to ChatActivity, it will trigger on onNewIntent() of SplashActivity. At this time, MainActivity is finished. 
I think it is not a good practice. The backstack like this
[SplashActivity -> MainActivity] -----(deeplink resolver)---> [SplashActivity-> ChatActivity]
Expectation: [SplashActivity-> MainActivity -> ChatActivity]

**Comment by radixdev** [comment]
Hi @laitr01 ,

You can customize the backstack behavior like so: https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#customizing-back-stack-behavior

You can also customize deeplink handling at a lower level at https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/deep_linking/

**Comment by punzalanrhemy** [comment]
> I have a problem when open deeplink from push notification like below:
> My application have three activities.
> SplashActivity -> MainActivity -> ChatActivity
> 
> I choose the splash screen to handle deeplink to a specific screen, so i set `singleTask` launch mode and for it.
> 
> ```
>          <intent-filter>
>                 <action android:name="android.intent.action.VIEW" />
> 
>                 <category android:name="android.intent.category.DEFAULT" />
>                 <category android:name="android.intent.category.BROWSABLE" />
> 
>                 <data android:scheme="app" />
>             </intent-filter>
> ```
> 
> * When the app was killed or running in background, i think everything works well.
> * When the app is on foreground, assumption i am stand at MainActivty and i click on push notification contains deeplink to ChatActivity, it will trigger on onNewIntent() of SplashActivity. At this time, MainActivity is finished.
>   I think it is not a good practice. The backstack like this
>   [SplashActivity -> MainActivity] -----(deeplink resolver)---> [SplashActivity-> ChatActivity]
>   Expectation: [SplashActivity-> MainActivity -> ChatActivity]
