### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by kaeawc** [Appboy/appboy-android-sdk#161]
This is one of the few third party libraries we use that doesn't have its artifacts published to Maven Central. I'd like to be able to remove our dependency on Braze's Github Page maven repository. I can understand if this isn't on your roadmap anytime soon, just want to advocate for it.

**Comment by radixdev** [comment]
Hi @kaeawc ,

We've looked into this before and ran into issues publishing the library there based on the closed source nature of the `android-sdk-base` module. We can reevaluate Maven Central's guidelines around publishing there, but afaik they haven't changed recently.

**Comment by kaeawc** [comment]
Ah okay - didn't realize there was a closed source piece.

Maybe Jitpack or Bintray would be a good alternative? The latter does not have restrictions on closed source, except that it probably means needing a paid account.

**Comment by radixdev** [comment]
Bintray was also looked at, sorry for not mentioning that before. However, from https://stackoverflow.com/a/30922472/3745724 , jcenter doesn't allow for closed source uploads either. We could upload to bintray (with a company specific link), but that would just replace our github repository with a braze branded bintray link and not be the more useful `jcenter()` approach.

**Comment by kaeawc** [comment]
Damn, that's annoying.

Feel free to close this then. Just wish there was a better path.
