### ISSUE TITLE
Migrate AppboyWebViewActivity to FragmentActivity

### ISSUE THREAD

**Issue by saurabharora90** [Appboy/appboy-android-sdk#166]
https://github.com/Appboy/appboy-android-sdk/blob/b3c64e97d51e3de45c494f99204910bb50b86dd9/android-sdk-ui/src/main/java/com/appboy/ui/activities/AppboyBaseActivity.java#L12

There is only one class which inherits from `AppboyBaseActivity` which is `AppboyWebViewActivity`. Any reasons for not making it a Fragment activity as well? The framework activity does not have Lifecycle component and hence we run into issues when loading deeplink metadata and having to dispose the network call if the user leaves the screen

**Comment by radixdev** [comment]
Hi @saurabharora90 ,

1. You can set a custom WebView Activity via https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/configuration/AppboyConfig.Builder.html#setCustomWebViewActivityClass-java.lang.Class- in the meantime.
2. Would `com.appboy.ui.activities.AppboyBaseFragmentActivity` be an appropriate class as the parent?
3. Can you elaborate on the issues you're seeing?

**Comment by saurabharora90** [comment]
- I'll explore (1)
- Yes `FragmentActivity` would be better. Not sure if that has any implications for you all
- When the `DefaultInAppMessageViewWrapper` bubbles up the click event to us, we try to deeplink to content that was being advertised. Since we only know the `id` of the content, we have to load it first via a API call. During this API call, the user might exit the screen so we need to tie into a Lifecycle owner to dispose the network call.

**Comment by radixdev** [comment]
I've created a story in our backlog to change the parent of the class. Thank you for the crash background.

Completely unrelated, would you mind filling out this androidX survey? https://forms.gle/RyLCWJMnxbMyHBGB7

**Comment by saurabharora90** [comment]
Thanks for considering. Looking forward to have ir resolved.

Filled out the survey :) Glad to see this is being considered.

**Comment by radixdev** [comment]
Thanks for your patience @saurabharora90 , this is now done in 10.1.0 of the SDK, released just now.
