### ISSUE TITLE
Property names are unreadable

### ISSUE THREAD

**Issue by sunilson** [Appboy/appboy-android-sdk#167]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

8.1.0

## What did you do?

Integrated the Braze SDK into my Android app

## What did you expect to happen?

Using classes like Card without having to guess what the property actually is.

## What happened instead?

Most property names are minified.

<img width="907" alt="Screenshot 2020-09-01 at 15 41 26" src="https://user-images.githubusercontent.com/8208775/91859099-5382f000-ec6a-11ea-908f-b5f0a7c0a9f6.png">

## Steps to reproduce

Add Braze SDK to Project and try loading ContentCards.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

**Comment by radixdev** [comment]
1. Are none of the methods listed at https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/cards/Card.html available for you?
2. Can you post your r8/proguard configuration?

**Comment by sunilson** [comment]
Thanks for your answer!

I think I was too quick with writing this issue, besides all those minified names there are also those that I can see in the documentation you sent. 

But still, it looks weird that there are so many randomly named properties/methods available.

**Comment by radixdev** [comment]
Upon deeper inspection in the mapping file it appears that those are all of the private fields of the Card object class that ProGuard has for some reason made available to view
