### ISSUE TITLE
Obfuscated card object in the SDK

### ISSUE THREAD

**Issue by DanielMartinus** [Appboy/appboy-android-sdk#168]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ]  I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

Latest version

## What did you do?

Implement observer for content cards

## What did you expect to happen?

To be able to retrieve information intuitively from a Card object.

## What happened instead?

![image](https://user-images.githubusercontent.com/1636897/95180383-2faf4e80-07c2-11eb-954b-de889d2308f2.png)

As you see in this image there's not really an API to safely retrieve the title, description or other information from a card object. I only see obfuscated properties. Is this intended or is there a different way of retrieving the values. I'm currently unsure if it's safe to retrieve the obfuscated properties because they look like they could change with a new release.

Also: could these objects perhaps not be obfuscated? That will make the sdk nicer to work iwth.

## Steps to reproduce

```Kotlin
if (contentCardsUpdatedSubscriber == null) {
    contentCardsUpdatedSubscriber = IEventSubscriber { event: ContentCardsUpdatedEvent ->
        val allCards = event.allCards

        // This card object seems to be obfuscated
    }
}
Appboy.getInstance(context).subscribeToContentCardsUpdates(contentCardsUpdatedSubscriber)
```

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

no

## Project that demonstrates the issue

n/a

# ANR Reporting

n/a

## Entire ANR Report

n/a

## Braze Related Threads In ANR

n/a

**Comment by radixdev** [comment]
Hi @DanielMartinus ,

Can you share your r8/proguard configuration? This looks like extra obfuscation being applied to the SDK. Our public API methods for a `Card` can be seen at https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/cards/Card.html.

**Comment by DanielMartinus** [comment]
Hi @radixdev, this is ran in debug mode where we don't apply any obfuscation to our builds

**Comment by radixdev** [comment]
Ah I see the issue here.

Card is the parent class of the actual typed card from the dashboard. In your screenshot, it appears that the card is actually a [TextAnnouncementCard](https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/cards/TextAnnouncementCard.html). To get the title easily, you'll have to cast the card. https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/cards/Card.html#getCardType-- is a helpful method to aid in determining the type of the card, using a switch statement for example.

**Comment by radixdev** [comment]
https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/models/cards/TextAnnouncementCard.html#getTitle-- for example would directly give you the title for the card

**Comment by DanielMartinus** [comment]
Got it! Thanks @radixdev
