### ISSUE TITLE
IAM showing inappropriate activity

### ISSUE THREAD

**Issue by hardbobby** [Appboy/appboy-android-sdk#169]
- [x] I have checked Braze's documentation and am have an issue with IAM.

# **Report**

## **What version of the Braze Android SDK are you using?**

`com.appboy:android-sdk-ui:8.0.1`

## **What did you do?**
I integrated Braze with the lifecycle listener on the application level
and create each page using `Tracking Custom Events` 
then create IAM and trigger on that event then show

## **What did you expect to happen?**
IAM showing only exactly custom event page

## **What happened instead?**
IAM showing on another page that not exactly the event name
example i put IAM on MainActivity with eventName `Main` and I create another with event name `product"`
`product` page opened from MainActivity .
then open APPS and open direct to `product` page but IAM `MainActivity` still showing

**Comment by radixdev** [comment]
Hello @hardbobby ,

This sounds like an integration issue rather than a bug. Can you please email `support@braze.com`? 

Thanks,
Julian
