### ISSUE TITLE
Image doesn’t display on Android 6

### ISSUE THREAD

**Issue by brozikcz** [Appboy/appboy-android-sdk#170]
Hi,

we use SDK version 8.1.0 and it works fine. But when we want to update the SDK to 10.1.0 the image in In-App Message (slideUpp variant) it doesn’t display on Android 6 (emulator; API 23, Google APIs, x86).
We don't use any `appboyImageLoader`.

![Snímek obrazovky 2020-10-13 v 15 53 19](https://user-images.githubusercontent.com/3849376/95878752-d91fb280-0d75-11eb-837b-f70ca95b4cf3.png)
![Snímek obrazovky 2020-10-13 v 17 01 38](https://user-images.githubusercontent.com/3849376/95878766-dd4bd000-0d75-11eb-9dd0-dfa3b08ca0dc.png)

[logcat.txt](https://github.com/Appboy/appboy-android-sdk/files/5372224/logcat.txt)

**Comment by radixdev** [comment]
hi @brozikcz ,

Can you provide exact steps to reproduce, along with any relevant code and URLs?

**Comment by radixdev** [comment]
Hi @brozikcz ,

We've identified the source of the issue and should have a fix available in the next release. In the meantime, you can use a custom image loader (such as Glide) to properly load images on API 23 and below.

**Comment by azri92** [comment]
@radixdev May I know when the next update will be released?

**Comment by radixdev** [comment]
Hi @azri92 ,

We roughly have a monthly release schedule so I'd say the next release shouldn't be very far away. I will update this issue once that release is done.

**Comment by azri92** [comment]
Cool. Looking forward to it

**Comment by punzalanrhemy** [comment]
``

**Comment by radixdev** [comment]
Hi @punzalanrhemy @azri92 @brozikcz ,

This is fixed in version 12.0.0 of the SDK, released just now. Thanks for your patience(s).
