### ISSUE TITLE
App Crashes when Opening a braze Campign

### ISSUE THREAD

**Issue by maheshmaersk** [Appboy/appboy-android-sdk#171]
Caused by java.lang.NullPointerException
Attempt to invoke interface method 'android.view.View com.appboy.ui.inappmessage.IInAppMessageViewWrapper.getInAppMessageView()' on a null object reference
com.appboy.ui.inappmessage.AppboyInAppMessageManager.unregisterInAppMessageManager
keyboard_arrow_down

* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## Project that demonstrates the issue

# ANR Reporting

**Comment by radixdev** [comment]
Hi @maheshmaersk ,

Can you please fill out the "Standard Reporting" portion of the issue template, thank you.

**Comment by radixdev** [comment]
Hey @maheshmaersk ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
