### ISSUE TITLE
Build failed because could not download android-sdk-ui-jetified-8.1.0.aar

### ISSUE THREAD

**Issue by doniwinata0309** [Appboy/appboy-android-sdk#172]
Hi, our gradle failed to download Braze SDK on Our CI:
> Could not download android-sdk-ui-jetified-8.1.0.aar (com.appboy:android-sdk-ui-jetified:8.1.0)
  > Could not get resource 'https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui-jetified/8.1.0/android-sdk-ui-jetified-8.1.0.aar'.
    > Could not GET 'https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui-jetified/8.1.0/android-sdk-ui-jetified-8.1.0.aar'.
      > Connection reset
        > Connection reset

This is intermittent issue, but failing lot of build on our CI in the past month. Any clue what we can do to fix it ?
Thank you in advance.

**Comment by radixdev** [comment]
Hi @doniwinata0309 ,

That artifact downloaded successfully for me just now. It's hosted on `github.io` so any connection issues would be traced back to there. If that connection issue with github.io cannot be debugged, I would recommend just downloading that AAR and referencing it directly in your project as a local resource instead of relying on the github hosted artifact.

**Comment by doniwinata0309** [comment]
Hi @radixdev  thank you for your reply. If we put it as local aar we need to also implement its dependencies manually which is not good because someone may not aware it is required by appboy, and accidentally remove it:
androidx.core:core:1.0.0
androidx.fragment:fragment:1.0.0
androidx.legacy:legacy-support-core-ui:1.0.0
androidx.legacy:legacy-support-core-utils:1.0.0
androidx.recyclerview:recyclerview:1.0.0
com.appboy:android-sdk-base-jetified:8.1.0

Secondly it is not convenient to update the library without artifactory. I am wondering if it is possible to also upload artifact to maven/apache so it can be available from mavenRepository or Jcenter ? Let me know what do you think about it. Thanks.

**Comment by radixdev** [comment]
We cannot upload our AAR to maven or jcenter given that our code is not 100% open sourced. 

This appears to be a connection issue with your CI system to `github.io` and not an issue with our artifact or something else we can directly address.

**Comment by doniwinata0309** [comment]
I see, thank you for your explanation. I guess i will close this issue for now.
