### ISSUE TITLE
Unable to change Card.isViewed to false

### ISSUE THREAD

**Issue by azri92** [Appboy/appboy-android-sdk#175]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
12.0.0

## What did you do?
After calling `Card.logImpression()`, I called `Card.setViewed(false)` when a user presses a button.

## What did you expect to happen?
Calling `Card.setViewed(false)` should change `Card.isViewed` to `false`.

## What happened instead?
`Card.isViewed` is still `true`.

## Steps to reproduce
1. Call `Card.logImpression()` on a card.
2. Call `Card.setViewed(false)` afterwards - either on button click or programmatic delay.
3. Check `Card.isViewed` value. It would be `true`.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
I'm using Card.isViewed to identify that a card has been `read`. I am trying to implement a "mark as unread" feature. Should I be using `Card.isIndicatorHighlighted` & `Card.setIndicatorHighlighted(Boolean)` instead?

## Project that demonstrates the issue
n/a

**Comment by radixdev** [comment]
Yes, if you would like to change the visual indicator and customize its appearance you should use `Card.isIndicatorHighlighted()` and not any of the viewed methods or fields

**Comment by azri92** [comment]
I see. Thank you!

**Comment by azri92** [comment]
@radixdev I'm not sure if this should be addressed to you, but hope you can point me to the right direction. It seems like the [iOS data model](https://appboy.github.io/appboy-ios-sdk/docs/interface_a_b_k_content_card.html) and the [Web data model](https://www.braze.com/docs/developer_guide/platform_integration_guides/web/content_cards/data_models/) does not have a similar "indicatorHighlighted" field. I'm trying to see how parity works in this case between the different platforms. Seems like the other platforms depend on the `viewed` field.

**Comment by radixdev** [comment]
Hi @azri92 ,

I would first check with our [documentation](https://www.braze.com/docs/developer_guide/home/) and if you can't find it there, I would open issues in https://github.com/Appboy/appboy-ios-sdk and https://github.com/Appboy/appboy-web-sdk respectively to see their methods.

**Comment by azri92** [comment]
Hi @radixdev ,

May I ask for details on why the `Card.setViewed(false)` does not work as per my initial report?

**Comment by radixdev** [comment]
Here's the code responsible for setting the viewed field:
```
  public boolean getViewed() {
    return mViewed;
  }

  public void setViewed(boolean viewed) {
    mViewed = viewed;
    if (mCardStorageProvider != null) {
      mCardStorageProvider.markCardAsViewed(mId);
    }
  }
```

I would assume that `setViewed` was re-invoked and changed the value of `mViewed` by the time you read it again. Regardless, `viewed` and its states are not what you want, the indicator highlight is.

**Comment by Bucimis** [comment]
Hi @azri92,

Unfortunately the ability to control indicator state directly does not exist on iOS or Web. We've logged this as a feature request for those SDKs.

**Comment by azri92** [comment]
> I would assume that setViewed was re-invoked and changed the value of mViewed by the time you read it again.

@radixdev Maybe would be best to include a disclaimer in the docs for the function because it seems like it's doing more than what the function says - not simply just setting the value.

I appreciate the suggestion to use the indicator highlight variable. It's just a bit challenging given that iOS & Web don't have the same.

**Comment by azri92** [comment]
> We've logged this as a feature request for those SDKs.

Thanks @Bucimis. Would be nice to be able to follow when it's ready for use.

**Comment by radixdev** [comment]
Hello @azri92 ,

I would recommend opening issues in those respective platform repositories so they can keep you updated on this feature request roadmap for those platforms. I'm closing this issue for now, thanks for filing!
