### ISSUE TITLE
What's the refresh rate of the content cards/news feed?

### ISSUE THREAD

**Issue by neugartf** [Appboy/appboy-android-sdk#176]
Hey!
Just a quick inquiry, if there is a mechanism that checks regularly on new content cards/news feed  (and in wich interval) or if we would need to manually call `requestContentCardsRefresh()` ourselves now and then. Haven't found anything in the docs regards this.

Thanks! :)

**Comment by Bucimis** [comment]
@neugartf the SDK automatically refreshes Content Cards on session start, when a new user logs in, and when the feed is viewed.
