### ISSUE TITLE
Fatal Exception: java.lang.VerifyError at runtime in BroadcastReceiver's onReceive

### ISSUE THREAD

**Issue by chun92** [Appboy/appboy-android-sdk#177]
* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

It occurs at over 10.0.0 version.
It doesn't occurs at 7.0.0

## What did you do?

I integrate braze and implement custom IInAppMessageManagerListener to control IAM.

## What did you expect to happen?

When the app receives push notification from braze, I expect that the app is open.

## What happened instead?

It got following errors and the app is crashed.

`2021-02-25 14:20:40.740 25307-25307/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: vixr.bermuda, PID: 25307
    java.lang.VerifyError: Verifier rejected class com.appboy.receivers.AppboyActionReceiver$a: boolean com.appboy.receivers.AppboyActionReceiver$a.a() failed to verify: boolean com.appboy.receivers.AppboyActionReceiver$a.a(): [0x9B] copy1 v3<-v0 type=Undefined cat=3 (declaration of 'com.appboy.receivers.AppboyActionReceiver$a' appears in base.apk)
        at com.appboy.receivers.AppboyActionReceiver.onReceive(SourceFile:4)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3392)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

## Steps to reproduce

- send a push notification
- open the app
- crash occurs

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

The error occurs only in release build, not in debug build.

## Project that demonstrates the issue

# ANR Reporting

**Comment by Bucimis** [comment]
Hi @chun92, we've had customers report similar issues due to R8 bugs. Could you try upgrading to Android Studio 4.2+ or R8 2.1.89+ and let us know if you still experience the issue?

**Comment by Bucimis** [comment]
(see https://issuetracker.google.com/issues/177929168#comment5)

**Comment by chun92** [comment]
Hi @Bucimis, We try your solution to upgrade R8 2.1.89+ and it works very well. Thank you.
