### ISSUE TITLE
Discrepancy between Modal and Custom Code in-app messages callbacks

### ISSUE THREAD

**Issue by deviant-studio** [Appboy/appboy-android-sdk#181]
# Standard Reporting

## What version of the Braze Android SDK are you using?

13.1.0

## What did you do?

Created 2 in-app messages in the braze console. 1 modal one and 1 with custom HTML code. Assigned some deep links to the in-app messages buttons
Implemented catching deep links with AppboyNavigator API. Implemented IAppboyNavigator handler

## What did you expect to happen?

When IAppboyNavigator.gotoUri(context: Context, uriAction: UriAction) triggers i expect to get an activity context in the callback. 

## What happened instead?

When IAppboyNavigator.gotoUri(context: Context, uriAction: UriAction) triggers i got different results for modal dialog/custom code dialog:
modal dialog -> got activity context in the callback
custom code -> got application context in the callback. so no way to implement fragments navigation without dirty hacks.

## Steps to reproduce

Implement deep links handler.
Run the custom code in-app message.
Check the `IAppboyNavigator.gotoUri()` received context param

AppboyInAppMessageViewLifecycleListener
![image](https://user-images.githubusercontent.com/1423947/113562425-b8426680-960e-11eb-932c-75a66987ddf1.png)

AppboyInAppMessageWebViewClientListener
![image](https://user-images.githubusercontent.com/1423947/113562525-e9229b80-960e-11eb-99a6-476c035a7997.png)

**Comment by radixdev** [comment]
Hi @deviant-studio ,

Thank you for filing this issue. This will be updated in the next release of the SDK. I will update this issue once that's live.
