### ISSUE TITLE
Redirecting to URL should not start APP

### ISSUE THREAD

**Issue by amit3vedi** [Appboy/appboy-android-sdk#183]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

13.0.0

## What did you do?

redirect to web URL when user click on notification button or click on notification

## What did you expect to happen?

user should be redirected to web URL

## What happened instead?

- App is starting and user is redirected to specified URL 
- Expected behaviour should be that App should not start if `Redirect to URL` is selected as notification/Action button click action
- user should only be redirected to default webbrowser of device No need to start app 

## Steps to reproduce
- add notification buttons in push notification or set click action to `Redirect to Web URL` and send push notification to user
- when you click on notification action App and webbrowser both will start 
- only webbrowser should start app should not start for external URL handling
 

## Project that demonstrates the issue

# ANR Reporting

**Comment by radixdev** [comment]
This is expected behavior and can be disabled via [disabling the backstack in our documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/integration/#customizing-back-stack-behavior)
