### ISSUE TITLE
changeUser() takes effect only when app fully restarted

### ISSUE THREAD

**Issue by deviant-studio** [Appboy/appboy-android-sdk#185]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What did you do?

First I logged as user no1
i called `Appboy.getInstance(context).changeUser(user1)`
Then I changed user to no2
`Appboy.getInstance(context).changeUser(user2)`

## What did you expect to happen?

I'm expecting that campaigns targeted for specifically that user no2 will trigger. 

## What happened instead?

Instead of that I still receive messages as user no1
After full app restart (process kill) i observe correct behavior. i receive messages targeted for user no2

## Steps to reproduce

Setup 2 campaigns targeted for 2 different users (user groups)
log in as user no1 
ensure you receive campaign no1 messages
log in as user no2 (via `appBoy.changeUser()`)
ensure you are still receiving campaign no1 messages despite campaign no2 should trigger

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

no

**Comment by radixdev** [comment]
Hi @deviant-studio ,

Can you email support@braze.com so you can share with them the dashboard campaign links and raw verbose logs? Those will all be needed to debug this properly.
