### ISSUE TITLE
BrazeProperties doesn't appear to exist in the `com.appboy:android-sdk-ui:14.0.0` SDK

### ISSUE THREAD

**Issue by tmtrademarked** [Appboy/appboy-android-sdk#190]
* [ X ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

14.0.0

## What did you do?

Attempted to replace uses of AppboyProperties with uses of BrazeProperties, as mentioned in the changelog.

## What did you expect to happen?

I expected the class `com.braze.BrazeProperties` to exist.

## What happened instead?

It does not appear to be included in the SDK artifact.

**Comment by radixdev** [comment]
Hi @tmtrademarked ,

This is resolved in 14.0.1 of the SDK, as you can see via https://appboy.github.io/appboy-android-sdk/javadocs/com/braze/models/outgoing/BrazeProperties.html
