### ISSUE TITLE
No com.braze.* in the actual android-sdk-ui-14.0.0.aar released or when built manually but in the javadoc.jar

### ISSUE THREAD

**Issue by plattnum** [Appboy/appboy-android-sdk#192]
No com.braze.* in here:
https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui/14.0.0/android-sdk-ui-14.0.0.aar 

Have com.braze.* in the javadoc.jar:
https://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui/14.0.0/android-sdk-ui-14.0.0-javadoc.jar

**Comment by radixdev** [comment]
Hi @plattnum ,

This is expected behavior based on how we generate our javadoc jar. It combines javadoc from the android-sdk-base and android-sdk-ui classpaths into a single javadoc. Is there a use-case you were trying to achieve and could not based on this setup?
