### ISSUE TITLE
Question about using Appboy.configure()

### ISSUE THREAD

**Issue by alvindizon** [Appboy/appboy-android-sdk#196]
Can configure() be called right after Appboy.getInstance() has been called? According to the [Javadoc](https://appboy.github.io/appboy-android-sdk/javadocs/), calling configure() would have no effect if the Appboy singleton is active, which is vague--does "active" mean getInstance has been called?

**Comment by Bucimis** [comment]
@alvindizon yep, configure() should be called before getInstance() is called to have an effect. And yep, your interpretation is correct, active means that getInstance() has been called and an initialized singleton exists. We'll explore making our documentation more precise

**Comment by alvindizon** [comment]
Thanks for the quick response @Bucimis !
