### ISSUE TITLE
HTML IAM with assets zip is not displayed (SDK 14.0.1)

### ISSUE THREAD

**Issue by lisional** [Appboy/appboy-android-sdk#197]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?

14.0.1

## What did you do?

We are trying a IAM HTML campaign (no preview) with a zip file attached containing some icons

## What did you expect to happen?

HTML should be displayed

## What happened instead?

The Event User log reports an **In-App Message Impression Failure**, IAM is not rendered in the app.

## Steps to reproduce

Setup an IAM Custom Code campaign with some assets in a zip file linked to it
Behavior is the same either using the 'Send test' feature or actually delivering the capaign to the targeted users.

Removing the zip fixes the issue, although images are not loaded in the HTML (obviously)

I have tried building 2 differents campaigns from scratch and observing this behaviour on both.
Behaviour is the same on all our Android tests devices.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
Here is the stacktrace

```
support.WebContentUtils  E  FileNotFoundException during unpack of zip file.
                         E  java.io.FileNotFoundException: /data/data/ca.lapresse.android.lapressemobile/cache/appboy-html-inapp-messages/-1232133628/image/connexion.png: open failed: ENOENT (No such file or directory)
                         E      at libcore.io.IoBridge.open(IoBridge.java:492)
                         E      at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
                         E      at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
                         E      at com.appboy.support.WebContentUtils.a(SourceFile:16)
                         E      at com.appboy.support.WebContentUtils.getLocalHtmlUrlFromRemoteUrl(SourceFile:12)
                         E      at com.appboy.ui.inappmessage.AppboyAsyncInAppMessageDisplayer.prepareInAppMessageWithZippedAssetHtml(SourceFile:8)
                         E      at com.appboy.ui.inappmessage.AppboyAsyncInAppMessageDisplayer.doInBackground(SourceFile:11)
                         E      at com.appboy.ui.inappmessage.AppboyAsyncInAppMessageDisplayer.doInBackground(SourceFile:1)
                         E      at android.os.AsyncTask$3.call(AsyncTask.java:394)
                         E      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                         E      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
                         E      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                         E      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                         E      at java.lang.Thread.run(Thread.java:923)
                         E  Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                         E      at libcore.io.Linux.open(Native Method)
                         E      at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
                         E      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
                         E      at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
                         E      at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8367)
                         E      at libcore.io.IoBridge.open(IoBridge.java:478)
```

**Comment by radixdev** [comment]
It appears that the zip file you're using is in an unexpected format.

1. Was this zip file created on a windows machine?
2. Does the zip file contain directories?
3. Can you provide a link to your campaign?

**Comment by lisional** [comment]
[original.zip](https://github.com/Appboy/appboy-android-sdk/files/6633641/original.zip)

Here is the zip

1. I don't know on which system it has been created, I'll asked our marketing team.
2. Well, there is a directory within the zip yes, I did not suspect this could cause such issue, if this is documented in the official documentation, sorry about posting here...
3. https://dashboard-06.braze.com/engagement/campaigns/608872e1d845fc5a1580fd38/5eaaf98bcad05965881722c1?locale=en&campaignName=feed_visible%20Android%20Fullscreen%20HTML&page=0

I'll try right now to remove the directory

Thank you for such a quick answer!

**Comment by lisional** [comment]
Well, zipping only files (no directories) seems to work.

This is a different behaviour than the iOS SDK, campaign was delivering fine on the iOS side. I'll update our marketing team about this behaviour on the Android side. Is it somewhere on your roadmap to homogenize this with iOS?

**Comment by radixdev** [comment]
The dashboard itself is supposed to prohibit asset zip files with directories, but depending on how the zip is created, that check can fail. Thus I'm not sure where we would state this in our documentation but I'll reach out.

**Comment by lisional** [comment]
Ok, the only warning I've seen from the console is when our zip exceeds a certain size (5Mo IIRC)
