### ISSUE TITLE
Background Crash in v 14.0.1

### ISSUE THREAD

**Issue by ewu-meetup** [Appboy/appboy-android-sdk#199]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
Version: 14.0.1

## What did you do?
updated version from 14.0.0 to 14.0.1

## What did you expect to happen?
No crashes in the background

## What happened instead?
crashes in the background:
`Fatal Exception: java.lang.NoSuchMethodError: No virtual method ()V in class Ljava/lang/Object; or its super classes (declaration of 'java.lang.Object' appears in /system/framework/core-oj.jar)
       at com.appboy.lrucache.AppboyLruImageLoader$b.run(AppboyLruImageLoader.java:13)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)`

`Device:
Brand:samsung
Model:Galaxy J7(2016)
Orientation: Portrait
RAM free: 449.16 MB
Disk free: 1.2 GB
Operating System:
Version:8.1.0`

**Comment by radixdev** [comment]
1. Do you have reproduction steps?
2. You can set a custom image loader via the documentation in https://www.braze.com/docs/developer_guide/platform_integration_guides/android/news_feed/gifs/#gifs if our default image loader doesn't work in your integration.

**Comment by ewu-meetup** [comment]
Hi Julian, thanks for the reply. I don't have the reproduction steps it is a background crash occurring every few minutes for a Galaxy J7(2016) running Android 8.1.0. Don't think it's an integration issue, was working fine on the previous version. looks like AppBoyLruImageLoader was recently depreciated.

**Comment by radixdev** [comment]
Hey @ewu-meetup ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further. We've added this to our internal backlog.
