### ISSUE TITLE
Question about "Event was published, but no subscribers were found. Saving event for later publishing to a matching subscriber. Event class: class com.appboy.events.SessionStateChangedEvent"

### ISSUE THREAD

**Issue by alvindizon** [Appboy/appboy-android-sdk#200]
We are currently trying out Braze in-app messaging campaigns via Braze dashboard. We've set up our app to send custom events to Braze, with the intention of using these custom events as triggers for our in-app messaging campaign to send messages to users. Now during the course of our testing, we noticed that the in-app message doesn't always appear when  our desired custom event has been hit. We checked the developer console and saw that the custom events were being sent successfully from the device to Braze, but the appearance of the in-app message was quite inconsistent.

Upon checking Logcat, we noticed the following messages: `Event was published, but no subscribers were found. Saving event for later publishing to a matching subscriber. Event class: class com.appboy.events.SessionStateChangedEvent`. It sounds like that an in-app message has been received by the app, but it wasn't displayed for some reason. What does this message mean?

Edit: would also like to add that our test campaign's re-eligibility is currently set to 0 minutes, so maybe there are some quotas/limitations on the API that we have to be aware about?

**Comment by Bucimis** [comment]
Hi @alvindizon,

That message is related to https://www.braze.com/docs/developer_guide/platform_integration_guides/android/analytics/tracking_sessions/#subscribing-to-session-updates, and basically notes that there are no subscribers for our externally facing session lifecycle events. It shouldn't have any impact on in-app messages.

Do you by chance have logcat output for both the working and non-working IAM case? Also, are you using `AppboyLifecycleCallbackListener` in your app to handle session and in-app message registration? https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/#activity-lifecycle-callback-integration

**Comment by alvindizon** [comment]
Hi @Bucimis, thanks for replying. I'm closing this ticket since the messages we've seen isn't related to in-app messages, plus we've fixed our campaign so now we can receive in-app messages 🤞 . Thanks!

**Comment by computerjazz** [comment]
@alvindizon mind sharing your fix? I'm in a similar situation -- we have an app that may trigger multiple event-based inAppMessages within a few seconds of each other. I have set a "0 minute" reeligibility on the campaign. Each event should trigger the same inAppMessage campaign, but only the first event actually results in the associated campaign being triggered. 

If I wait ~1min before triggering the second event I see the campaign re-triggered.

**Comment by alvindizon** [comment]
Hi @computerjazz , yeah we saw that minimum interval too, but decided against overriding it as we realized that we don't need to send messages within seconds of each other 🤷‍♂️ What tripped us up was that we were using the wrong letter case for   some of the filters we used in the Braze campaign dashboard, that's why we had inconsistent results.
