### ISSUE TITLE
Warning: None of the selected users have matching push tokens for Android Push

### ISSUE THREAD

**Issue by shethabhish** [Appboy/appboy-android-sdk#205]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## What version of the Braze Android SDK are you using?
I'm actually using React Native SDK setup, but I'm working on the Push Setup for Android, we're using the latest braze sdk(16.0.0)

## What did you do?
I followed the setup on this page, I did Step 1: Enable Firebase, Step 2: Configure Token Registration(OPTION 1: AUTOMATIC REGISTRATION), Step 4: Set Your Firebase Credentials, Step 5: Remove Old Permissions. Then I did Step 1: Register Braze Firebase Messaging Service and Step 4: Add Deep Links. Those are all the steps I performed.

## What did you expect to happen?
I expected it to show the push notification on the emulator and the device.

## What happened instead?
It shows: Warning: None of the selected users have matching push tokens for Android Push. The push worked 3 to 4 weeks back but not now. The below are push settings of the user
![image](https://user-images.githubusercontent.com/20106435/141494218-12664621-517b-4208-8dc6-7eb48156b939.png)

Also I recall couple of weeks back there wasn't this SDK Authentication
![image](https://user-images.githubusercontent.com/20106435/141494321-409a0358-5759-4fcb-bdba-64688b28759e.png)

## Steps to reproduce
Just do the exact steps I mentioned in "What did you do?" question.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
No

## Project that demonstrates the issue
I unfortunately cannot provide it.

# ANR Reporting

**Comment by Bucimis** [comment]
@shethabhish If you enable verbose logs, you should be able to trace the lifecycle of push related events in the SDK. Once registered, the SDK should log that it is sending a `push_token` field to the Braze backend. For more assistance on this and ability to communicate in a more private environment, I would recommend reaching out to support@braze.com.
