### ISSUE TITLE
what dependency should i define in build.gradle to extend com.appboy.unity.AppboyUnityPlayerActivity

### ISSUE THREAD

**Issue by shanukp** [Appboy/appboy-android-sdk#206]
* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.
* [ ] I have an ANR related issue and have filled out the "ANR Reporting" section below.

# Standard Reporting

## Project that demonstrates the issue

# ANR Reporting

**Comment by shanukp** [comment]
its routing me to import com.appboy.unity.prime31compatible.AppboyUnityPlayerActivity; with which getIntent() etc fails

**Comment by Bucimis** [comment]
If building from within Unity, things should work - i.e. `com.unity3d.player.UnityPlayerActivity` should be available in your path.

If building external from Unity, you may need to add the Unity jar manually to your project.

**Comment by radixdev** [comment]
Hi @pletoss ,

This was fixed in version 3.7.0 of the Unity SDK, released today. Thanks for filing!
