### ISSUE TITLE
DisableSdk issue

### ISSUE THREAD

**Issue by pchelnikov-alar** [Appboy/appboy-android-sdk#207]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/initial_sdk_setup/android_sdk_integration/) and am still experiencing the issue.

# Standard Reporting

## What version of the Braze Android SDK are you using?

1.17.0

## What did you do?

Setup new API key for Braze

## What did you expect to happen?

Braze will replace old configurations with new ones

## What happened instead?

**First:** I'm checking:
```
        if (!Braze.isDisabled()) {
            Braze.disableSdk(applicationContext)
        }
```
**After:** I setting new braze configuration (with new api key)
```
val brazeConfig = BrazeConfig.Builder()
        .setApiKey("new-api-key")
        .setCustomEndpoint("ENDPOINT")
        .setSessionTimeout(60)
        .setHandlePushDeepLinksAutomatically(true)
        .setGreatNetworkDataFlushInterval(10)
        .build()
Braze.configure(this, brazeConfig)
```
**After:** Braze logs:

 I/Braze v17.0.0 .com.braze.configuration.RuntimeAppConfigurationProvider: Setting Braze Override configuration with config...
 **W/Braze v17.0.0 .com.braze.Braze: SDK is disabled. Actions will not be performed on the SDK.**

**Comment by bryanlogan** [comment]
You need to call Braze.enableSdk(applicationContext) when you're done.  https://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/Appboy.html#enableSdk-android.content.Context-
