### ISSUE TITLE
Jetpack Compose Support

### ISSUE THREAD

**Issue by Fintasys** [Appboy/appboy-android-sdk#208]
I would like to know if there are any plans for Jetpack Compose support in near future?

In our new App that is completely build of Jetpack Compose components (UI, Navigation, etc) we still need to use XML layouts for our customized views like In-App-Modal and implement a custom Braze Navigator to work with the new compose navigation. 

Technically it is working, but preference would be to have support for it to avoid workarounds. 

Thank you!

**Comment by radixdev** [comment]
Hi @Fintasys ,

We don't current have Jetpack Compose support on our roadmap but we are currently in the process of rewriting our SDK into Kotlin, which will make potential features like Jetpack Compose much easier to interop with.

Can you share your current compose navigation workaround and what your future ideal integration path for compose navigation & Braze looks like?

Thanks!

**Comment by Fintasys** [comment]
Oh sorry for the late reply!

Ah I see, too bad. Thank you for the information!

About the workaround, we haven't found a way to directly access compose navigation with `AppboyNavigator`. So we made a custom Implementation of it and just creating and starting normal intents inside `gotoUri`. Compose Navigation then will handle the intent and open the associated screen. The disadvantage of this method is that the transition isn't as smooth as if we use compose navigation directly - all compose components need to be recreated with this method.

Here is a code snipped to make it more clear:
WebView-Screen-Navigation
```
fun NavGraphBuilder.webViewNavigation(
    navController: NavController,
) {
    composable(
        route = "....",
        arguments = listOf(
            ...
        ),
        deepLinks = listOf(
            navDeepLink {
                uriPattern = DEEPLINK_PATTERN
            },
        )
    )
```
Custom BrazeNavigator
```
    override fun gotoUri(context: Context, uriAction: UriAction) {
        Timber.d("Executing Uri action from Channel ${uriAction.channel}: Extras: ${uriAction.extras}")

        // Let Braze handle open website requests (non-AppLink)
        if (uriAction.useWebView) {
            return super.gotoUri(context, uriAction)
        }

        deepLinkIntent?.action = Intent.ACTION_VIEW
        deepLinkIntent?.data = uriAction.uri

        taskStackBuilder
            .addNextIntentWithParentStack(deepLinkIntent)
            .getPendingIntent(0, PendingIntent.FLAG_UPDATE_CURRENT)
            ?.send() ?: throw IllegalStateException("Failed to send deep link pending intent is null")
    }
```

**Comment by radixdev** [comment]
Moved to https://github.com/braze-inc/braze-android-sdk/issues/2
