### ISSUE TITLE
AppboyUnityPlayerActivity final by default, can't be extended anymore

### ISSUE THREAD

**Issue by pletoss** [Appboy/appboy-android-sdk#209]
Dear Braze Team,

The current Braze release 3.6.0 had a breaking change which resulted in us not being able to extend the AppboyUnityPlayerActivity by sublassing it, as described in https://www.braze.com/docs/developer_guide/platform_integration_guides/unity/sdk_integration/android/#extending-braze-unity-player 

I assume it's due to the refactor to a kotlin class, which by default has are final: 

https://github.com/Appboy/appboy-android-sdk/blob/e97b12a2078e8ab614e1bb866c2ab7dac806d41e/android-sdk-unity/src/main/java/com/appboy/unity/AppboyUnityPlayerActivity.kt#L15

In case it was intentional, I would be interested how else we can extend this with our own functionality. 

Thanks.

**Comment by radixdev** [comment]
Hello @pletoss ,

This was a bug on our part. We will be fixing this in our next android and Unity releases. Thanks for bringing this to our attention!

**Comment by radixdev** [comment]
Hi @pletoss ,

This was fixed in version 3.7.0 of the Unity SDK, released today. Thanks for filing!
