### ISSUE TITLE
AppboyProperties class doesn't exist anymore

### ISSUE THREAD

**Issue by Hassanmohsaid** [Appboy/appboy-android-sdk#212]
The project was working fine until yesterday, but since today I can't build it

Version: latest (18.0.+)

I tried to clean the project and get dependencies again.

```
error: cannot find symbol
import com.appboy.models.outgoing.AppboyProperties;
                                 ^
  symbol:   class AppboyProperties
  location: package com.appboy.models.outgoing
```

**Comment by Bucimis** [comment]
@Hassanmohsaid that class has been renamed to `com.appboy.models.outgoing.BrazeProperties`, let us know if renaming doesn't solve your issue!
