### ISSUE TITLE
Facing lint error "setHasFixedSize() in recyclerview" when producing release apk

### ISSUE THREAD

**Issue by purnima-mishipay** [Appboy/appboy-android-sdk#214]
I have used appboy android sdk 18.0.0

I am getting following lint error when producing release build -  
Error: When using `setHasFixedSize() in an RecyclerView, wrap_content cannot be used as a value for size in the scrolling direction. [InvalidSetHasFixedSize]

This error isn't raised in the same code without appboy.

How should I handle it?

**Comment by radixdev** [comment]
Hi @purnima-mishipay ,

We do not call `setHasFixedSize()` in our SDK in code nor in our xml styles configuration. See [ContentCardsFragment](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/braze/ui/contentcards/ContentCardsFragment.java) and our [relevant styles ](https://github.com/Appboy/appboy-android-sdk/blob/64774c3c64b5481e758de8f518ef56bdbdf4432d/android-sdk-ui/src/main/res/values/styles.xml#L515-L530). 

I would investigate any custom styles file overrides in your application and any other SDK dependencies in your project.

**Comment by purnima-mishipay** [comment]
setHasFixedSize() is used in my code for some recyclerviews.

**Comment by radixdev** [comment]
Hi @purnima-mishipay ,

You can override our [default styles](https://github.com/Appboy/appboy-android-sdk/blob/64774c3c64b5481e758de8f518ef56bdbdf4432d/android-sdk-ui/src/main/res/values/styles.xml#L515-L530) to change the `wrap_content` field in your application. You can also ensure that you're not calling `setHasFixedSize` on any Braze RecyclerViews in conjunction with that guidance.
