### ISSUE TITLE
[Bug]: Push notifications do not work in API 33/Android 13

### ISSUE THREAD

**Issue by alvindizon** [Appboy/appboy-android-sdk#223]
### Braze Android SDK Version

19.0.0

### Steps To Reproduce

Android 13 debuts a new permission for showing notifications, see [here](https://developer.android.com/about/versions/13/changes/notification-permission) for details. 

1.  Since our app targets API 31, installing and opening our app on an Pixel 4 running Android 13 / Tiramisu results in the system showing a permissions dialog. We selected "Allow"
2. In the Braze dashboard, I edited an existing campaign and sent a test message to our device

### Expected Behavior

Push notification message should appear

### Actual Incorrect Behavior

No push notification appeared.

**Comment by Bucimis** [comment]
Hi @alvindizon,

Thanks for getting in touch. Do you have verbose logs illustrating the issue on your device? Also, can you confirm whether  1) the app is receiving the push notification but the SDK is failing to display it, or 2) the app never receives the push notification

Feel free to mail your logs to support@braze.com if they contain sensitive information.

Thanks!

**Comment by radixdev** [comment]
@alvindizon can you also post the Android 13 preview version you are using? (e.g. DP1, DP2, Beta 1, etc.)

**Comment by alvindizon** [comment]
Hi @radixdev @Bucimis , sorry for the late reply. I tried to test our app again in Android 13 and sent test push notifs and in-app messages via Braze dashboard and strangely enough, push notifications and in-app messages successfully come through this time. I'm using an Android emulator BTW (Pixel 4).

Will keep an eye out for any further issues but for now, I'll close this. Thanks
