### ISSUE TITLE
[Bug]: ContentCardsUpdatedEvent user is empty even tho user is logged in

### ISSUE THREAD

**Issue by Fintasys** [Appboy/appboy-android-sdk#233]
### Braze Android SDK Version

23.0.1 and previous

### Steps To Reproduce

Example code
```
                contentCardsUpdatedSubscriber = IEventSubscriber { event ->
                    // Received Data
                    Log.wtf("BrazeTest", "ContentCard: ${event}")
                }
                Log.wtf("BrazeTest", "Current Braze User: ${brazeInstance.currentUser?.userId}'")
                Log.wtf("BrazeTest", "subscribeToContentCardsUpdates")
                brazeInstance.subscribeToContentCardsUpdates(
                    contentCardsUpdatedSubscriber!!
                )
                brazeInstance.requestContentCardsRefresh(false)
```
                

### Expected Behavior

ContentCard request returns ContentCards for current User

### Actual Incorrect Behavior

<img width="980" alt="Screen Shot 2022-08-17 at 15 14 13" src="https://user-images.githubusercontent.com/11667234/185047866-af727e48-47f6-4c20-926a-51969ee73ba2.png">

### Verbose Logs

The verbose logs show that the SDK returns the cached entry even although I request `fromCache = false`
<img width="1262" alt="Screen Shot 2022-08-17 at 15 28 14" src="https://user-images.githubusercontent.com/11667234/185050023-bf7052ce-bc4e-404e-8046-5e57589c5d15.png">

### Additional Information

I can only replicate this issue in our code base, when I try it in a separate project only with Braze SDK it works as intended. 
Nevertheless, the code looks like posted above. It seems even although I request `fromCache = false` it returns cached data at first. The test was made after a fresh install.

**Comment by radixdev** [comment]
Hi @Fintasys ,

We've added this to our current sprint for investigation and will update you with any updates. The SDK has a mechanism to publish old events fired before any listener was set (i.e. the "publishing cached event" log you see). In the meantime, you can check if the [content cards event userId](https://appboy.github.io/appboy-android-sdk/kdoc/braze-android-sdk/com.braze.events/-content-cards-updated-event/index.html#-1290425080%2FProperties%2F-1725759721) matches that of the logged in user before using the event.

**Comment by bryanlogan** [comment]
@Fintasys ,

I'm thinking the empty userID event is created when things are initiated, and then when you switch userID, another event should be created. Can you let me know if that other event is received?

**Comment by Fintasys** [comment]
@bryanlogan From my testings the flow was like this
1. Start App (clean state)
2. Switch User (signUp)
3. Request ContentCard Update
4. Receive empty result (user also empty)
5. Receive result with data and user

Does that answer your question?

**Comment by Fintasys** [comment]
Note sure if it is related to this but do you have an explanation why it takes many requests until the content cards that are segmented to `all users` / `external-id is empty` (not sure if that's the same when user freshly installs the app) to be returned from the API ? I would expect that all content cards that matches segment of `all users` / `external-id is empty` are returned from the very first API call. 
<img width="1293" alt="Screen Shot 2022-08-25 at 18 21 28" src="https://user-images.githubusercontent.com/11667234/186628751-9dac23d5-5f08-48d2-88dd-cd24777080b1.png">
In the screenshot above I was able to get 1 campaign (segment `external-id empty` to be returned after 20 seconds. Campaigns with segment `all users` were not returned immediately, still can't find out why they only get returned sometimes after a while.

**Comment by bryanlogan** [comment]
We've made a fix for this that should lessen the number of old updates you'll see.  However, there are still scenarios where you might see the old ones, so you should continue to check userid. It should be released during our next regular update, but you shouldn't have to do anything different in your code since you should continue to check.
