### ISSUE TITLE
[Bug]: DefaultInAppMessageViewWrapper is not inheritable anymore

### ISSUE THREAD

**Issue by snappdevelopment** [Appboy/appboy-android-sdk#235]
### Braze Android SDK Version

23.1.0

### Steps To Reproduce

In 23.1.0 the [DefaultInAppMessageViewWrapper](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/braze/ui/inappmessage/DefaultInAppMessageViewWrapper.kt) got converted from Java to Kotlin which can be seen [here](https://github.com/Appboy/appboy-android-sdk/compare/v23.0.1...v23.1.0).

In Java this class can be inherited from to implement a custom version of it. This is not possible anymore since Kotlin classes are final by default.

### Expected Behavior

[DefaultInAppMessageViewWrapper](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/braze/ui/inappmessage/DefaultInAppMessageViewWrapper.kt) should be inheritable.
This could be fixed by adding the `open` keyword to the class.

### Actual Incorrect Behavior

[DefaultInAppMessageViewWrapper](https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/main/java/com/braze/ui/inappmessage/DefaultInAppMessageViewWrapper.kt) is final and can't be inherited.

**Comment by radixdev** [comment]
Hi @snappdevelopment ,

We will have a fix available soon and will update this issue with any updates. Thank you for filing!

**Comment by radixdev** [comment]
Hi @snappdevelopment ,

This is fixed in 23.1.1 of the SDK.
