### ISSUE TITLE
[Feature]: Publish on maven central

### ISSUE THREAD

**Issue by wartingep** [Appboy/appboy-android-sdk#237]
### What problem are you facing?

Please deploy the library on maven central.

### Workarounds

N/A

### Ideal Solution

Not having a custom repository to https://appboy.github.io/appboy-android-sdk/sdk

**Comment by radixdev** [comment]
Hello @wartingep ,

We will re-investigate adding our library to maven central. In the past there have been issues or unresolved questions about adding a partially closed source library to sonatype but we will get back to you if that has changed. https://issues.sonatype.org/browse/MVNCENTRAL-692 🤞🏽

**Comment by gabrielittner** [comment]
Is there any update on this? We'd also prefer to not have a custom repo for braze

**Comment by radixdev** [comment]
Hi @gabrielittner ,

We have the groundwork for this scheduled for our next sprint and will update you as this project moves along.

**Comment by radixdev** [comment]
Moved to https://github.com/braze-inc/braze-android-sdk/issues/1

**Comment by radixdev** [comment]
Hello all,

We're now available on [Maven Central](https://repo.maven.apache.org/maven2/com/braze/) as of version 25.0.0 of the Braze Android SDK. 

Thank you for your patience on this journey,
Braze
