### ISSUE TITLE
Can not track Custom Events in 21.0.0

### ISSUE THREAD

**Issue by logosmjt** [Appboy/appboy-android-sdk#239]
### Braze Android SDK Version

21.0.0

### Steps To Reproduce

Upgrade braze sdk to 21.0.0 from 13.1.2.
**Custom Events** can not be tracked in https://...braze.com/api/v3/data.

### Expected Behavior

Custom Events can be tracked.

### Actual Incorrect Behavior

Custom Events were missed in https://...braze.com/api/v3/data.

**Comment by davidbielik** [comment]
Hi @logosmjt there is not enough information here to understand or reproduce what's going on. Please reply with steps to reproduce, verbose logs, and more detail about expected vs. actual behavior.

**Comment by logosmjt** [comment]
Hi @davidbielik , we created some custom events on braze GUI.

Before:
App works on braze 13.1.2.
On the screen, we can trigger custom events as follows.
https://xxx.xxx.braze.com/api/v3/data
```
{
	"time": 1663635213,
	"api_key": "...",
	"sdk_version": "13.1.2",
	"app_version": "...",
	"attributes": [{
		"custom": {
		},
		"user_id": "..."
	}],
	"events": [{
		"name": "ce",
		"data": {
			"n": "...",
			"p": {
				"p1": "xxx",
				"p2": "xxx",
				"p3": "xxx"
			}
		},
		"time": 1.663635163089E9,
		"user_id": "xxx",
		"session_id": "xxx"
	}],
	"respond_with": {
		"user_id": "xxx",
		"config": {
			"config_time": 1663582840
		}
	}
}
```

After:
The app works on braze 21.0.0 with the similar config.
On the screen, I can not get anything from Charles.
