### ISSUE TITLE
 Does Braze.getInstance() using getBrazeLogTag() internally? As, it is causing me issues while mocking Braze.getInstance(), linked with: https://github.com/Appboy/appboy-android-sdk/issues/241

### ISSUE THREAD

**Issue by gitanshubatra239** [Appboy/appboy-android-sdk#242]
### Braze Android SDK Version

23.1.1

### Steps To Reproduce

Mock Braze.getInstance(mocked_context) on static instance 
While executing this mock, an error occurs: Braze cannot be returned by getBrazeLogTag(). It should return string.

### Expected Behavior

While Mocking Braze.getInstance() , There should be some info if it is calling getBrazeLogTag() internally. and If it is calling, what object used to call this method so that we can mock that object.

### Actual Incorrect Behavior

Braze.getInstance() using getBrazeLogTag() internally

**Comment by radixdev** [comment]
Hi @gitanshubatra239 ,

Mocking the production SDK in the manner you describe is a product request and should be routed to your CSM.
