### ISSUE TITLE
[Feature]: Need workaround related to basic unit testing of Braze

### ISSUE THREAD

**Issue by gitanshubatra239** [Appboy/appboy-android-sdk#243]
### What problem are you facing?

 **@Mock**
  private lateinit var context: Context
  **@Mock**
  private lateinit var brazeInstanceMock: Braze
  
**brazeMock = mockStatic(Braze::class.java)
  `when`(context.applicationContext).thenReturn(applicationMock)
  brazeMock.`when`<Braze> { Braze.getInstance(context) }.thenReturn(brazeInstanceMock)**

**This is the mocking that I am applying, and getting the following error :** 
org.mockito.exceptions.misusing.WrongTypeOfReturnValue: 
Braze cannot be returned by **getBrazeLogTag()**
**getBrazeLogTag()** should return String

### Workarounds

I tried to mock getBrazeLogTag(), it didn't work.

### Ideal Solution

Please provide some basic unit test integration code or links that will show how to mock Braze instance & some methods of Braze Class so that our issue could get resolved.

**Comment by gitanshubatra239** [comment]
Hi, any update on this ticket please?

**Comment by radixdev** [comment]
Hi @gitanshubatra239 ,

Mocking the production SDK in the manner you describe is a product request and should be routed to support instead of a Github Issue.
