### ISSUE TITLE
[Bug]: getRegisteredPushToken() and setRegisteredPushToken() don't exist

### ISSUE THREAD

**Issue by Odaym** [Appboy/appboy-android-sdk#249]
### Braze Android SDK Version

23.3.0

### Steps To Reproduce

Using Braze SDK (ui) 23.3.0, try to use `Braze.setRegisteredPushToken()` or `Braze.getRegisteredPushToken()`, these methods do not exist and they should exist based on the [changelog for Braze SDK version 22.0.0 ](https://www.braze.com/docs/developer_guide/platform_integration_guides/android/changelog/#2200).\

They are supposed to replace `AppBoy.getInstance().registerAppboyPushMessages()` but they do not exist at all, only the property `Braze. registeredPushToken` exists.

### Expected Behavior

These methods don't exist, not in `23.3.0` nor in `22.0.0` where the change was supposedly introduced.

### Actual Incorrect Behavior

These methods should exist.

**Comment by Bucimis** [comment]
@Odaym are you using Kotlin? If so, use the property `Braze.registeredPushToken` (https://github.com/Appboy/android-sdk/blob/5958b60bc51c0a9b95e3ea7869940471cdf31223/public/root-directory-files/CHANGELOG.md#breaking-2)
