### ISSUE TITLE
Background color is not reflecting in braze push notification small icon

### ISSUE THREAD

**Issue by Ankit-Kr-Verma** [Appboy/appboy-android-sdk#251]
### Braze Android SDK Version

18.0.0

### Steps To Reproduce

Added drawable svg format for small icon

Added braze.xml in res/values folder and defined push notification small icon and color in braze.xml as below
  <drawable name="com_braze_push_small_notification_icon">@drawable/ic_notification_icon</drawable>
  <integer name="com_braze_default_notification_accent_color">0xf78d00</integer>

Initialised the BrazeConfig in application class onCreate() as:
val brazeConfig = BrazeConfig.Builder()
                .setApiKey(BuildConfig.BRAVE_API_KEY)
                .setSmallNotificationIcon(applicationContext.resources.getResourceEntryName(R.drawable.ic_notification_icon))
                .setPushDeepLinkBackStackActivityEnabled(true)
                .setIsFirebaseCloudMessagingRegistrationEnabled(true)
                .setFirebaseCloudMessagingSenderIdKey(BuildConfig.FIREBASE_TOKEN)
                .build()
        Braze.configure(applicationContext, brazeConfig)
        registerActivityLifecycleCallbacks(BrazeActivityLifecycleCallbackListener())
        

### Expected Behavior

The push notification small icon should come with background color

### Actual Incorrect Behavior

small icon is coming as expected but the background color is not reflecting. 
Tested in emulator:  Pixel 3 XL Android 9, Nexus 5X Android 10, Pixel 2 Android 11, Pixel 3a XL Android 12
Please find the attach screenshot.

<img width="389" alt="Screenshot 2022-12-12 at 5 04 23 PM" src="https://user-images.githubusercontent.com/12911282/207035576-c077d178-796b-4a7c-be5e-6f4ed304df48.png">

### Additional Information

Can you please look into this issue. As all steps have been done as per the documentation still the background color is not reflecting for the braze push notification small icon.

**Comment by radixdev** [comment]
1. Can you provide the original `png` for the icon you're trying to use?
2. Please go over https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-2-ensure-small-icons-conform-to-design-guidelines and ensure your icon follows the OS guidelines. What you're seeing is likely to be OS behavior and not something the SDK can override.

**Comment by Ankit-Kr-Verma** [comment]
Hi @radixdev, 
I'm using the svg for the small icon not png format and it is as per the android design guidelines. Due to company policy not able to share the original svg icon now, will check if I can do that. 
If possible can you please confirm in the emulator, the svg icon with background color will work for braze push notification small icon or not.

**Comment by radixdev** [comment]
Hi @Ankit-Kr-Verma ,

Without the exact SVG file, we cannot reproduce your issue. If you can provide another SVG that reproduces the issue (e.g. not one from your company or violates your company policies) then we can proceed with the investigation.
