### ISSUE TITLE
[Bug]: Fetching the device id may block the main thread

### ISSUE THREAD

**Issue by fleficher** [Appboy/appboy-android-sdk#252]
### Braze Android SDK Version

23.2.1

### Steps To Reproduce

Get the device id from anywhere.

```kotlin
Braze.getInstance(context).deviceId
```

### Expected Behavior

The method should be documented as blocking and have an async version like for the `getCurrentUser`.

### Actual Incorrect Behavior

Fetching the `deviceId` may block the main thread for some ms.
We've seen that calling this method at startup impacted our app startup time metrics.
![image](https://user-images.githubusercontent.com/6464646/207372271-76aa87c3-d2a4-4573-8003-480f22ec3688.png)

The method seems to call `runBlocking` which is usually used to be used outside the main thread.
Can you confirm if this method can slow down apps if called at startup?

**Comment by radixdev** [comment]
Yes @fleficher you are correct that the method is blocking and needs documentation/async. I've filed a story to do the above. Thank you!

**Comment by radixdev** [comment]
Hi @fleficher .

We've added a new method to async get the device id in release 25.0.0.
