### ISSUE TITLE
[Bug]: Image on content card is exploding while scrolling

### ISSUE THREAD

**Issue by vinaykumar2197** [Appboy/appboy-android-sdk#256]
### Braze Android SDK Version

24.2.0

### Steps To Reproduce

1.  Make sure you have 15+ campaigns 
2. Try to scroll the page 2/3 times 
3. I got this issue on pixel device.

### Expected Behavior

While the recyclerview is being scrolled, image shouldn't explode instead it should show the images properly. 

### Actual Incorrect Behavior

 image is exploding

### Verbose Logs

```shell
Provided the link of log file in additional section
```

### Additional Information

<img width="359" alt="Screen Shot 2023-01-30 at 8 42 36 PM" src="https://user-images.githubusercontent.com/37454516/215494339-85a7320a-10a5-46f6-bb10-c392fea358f6.png">
[log_verbose.txt]()

**Comment by vinaykumar2197** [comment]
Hey @bryanlogan ,
Thank you for responding. I am currently using com.braze.ui.contentcards.ContentCardsFragment view to render the content card which is provided by braze. "ImageView dimensions cannot be 0. Not resizing ImageView" this is coming from braze sdk. I think image is not being scaled properly, or there is some exception where we are printing the above log. 
I think BrazeImageUtils class can give us more info on this.

**Comment by bryanlogan** [comment]
We give that error if the height or width of the ImageView is 0.  I've tried recreating this and haven't been successful.  Does it recreate on Droidboy (the sample application with the SDK)?

**Comment by radixdev** [comment]
Hey @vinaykumar2197 ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
