### ISSUE TITLE
How can I Initialize Braze in runtime?

### ISSUE THREAD

**Issue by Holoceo** [Appboy/appboy-android-sdk#257]
### What problem are you facing?

I need to set api_key and endpoint in runtime. Can I do it somehow?

### Workarounds

I haven't found any workarounds

**Comment by bryanlogan** [comment]
Does this example help? https://github.com/Appboy/appboy-android-sdk/blob/master/samples/hello-braze/src/main/java/com/braze/helloworld/CustomApplication.java

And our documentation here: https://www.braze.com/docs/developer_guide/platform_integration_guides/android/advanced_use_cases/runtime_configuration

**Comment by Holoceo** [comment]
@bryanlogan thank you so much!
