### ISSUE TITLE
[Bug]: Notification Icon is not display properly on Android 13

### ISSUE THREAD

**Issue by CHRehan** [Appboy/appboy-android-sdk#263]
### Braze Android SDK Version

15.0.0
### Steps To Reproduce

The notification Icon is not displayed properly on Android 13
![3bb54780-368a-462c-859b-1b747bf7738e](https://github.com/Appboy/appboy-android-sdk/assets/12581323/b6488110-7ab0-4f29-9398-83d1c015ad1d)

### Expected Behavior

The notification Icon is not display properly on Android 13

### Actual Incorrect Behavior

The notification Icon is not display properly on Android 13

**Comment by radixdev** [comment]
Hi @CHRehan ,

1. Have you taken a look at https://www.braze.com/docs/developer_guide/platform_integration_guides/android/push_notifications/android/integration/standard_integration/#step-2-conform-small-icons-to-design-guidelines ?
2. Can you upload the png file you're using here so we can inspect it?

Thanks,
Julian

**Comment by CHRehan** [comment]
Hello @radixdev ,
Thanks for your reply. I have not set the custom notification icon. It's working fine on below android 13. To set the custom notification icon, Should we also update the braze SDK version to 24, we are on 15.0.0.

**Comment by radixdev** [comment]
1. Can you upload the png file you're using here so we can inspect it?
2. Can you share your `braze.xml` or BrazeConfig configuration?
