### ISSUE TITLE
[Bug]: countOccurrences problem

### ISSUE THREAD

**Issue by hamish-snoop** [Appboy/appboy-android-sdk#264]
### Braze Android SDK Version

com.appboy:android-sdk-base:23.0.1

### Steps To Reproduce

`this.countOccurrences("</li>")` 

where this is:
`"<li>Your deal ends on 11 October. Now's the time to look for a new one otherwise you'll be rolled onto an expensive contract.</li><li>I'll help you check how much you're paying vs the best prices on the market.</li><li>If you switch your broadband through me, you'll get a £20 Amazon voucher. <a href=\"https://snoop.app/broadbandterms/\">Read the terms.</a></li><li>If you're in contract, check for exit fees.</li><li>Switching is easy - the max time it takes is usually 10 days and you'll only have around 2 hours of downtime.</li><li>Most people can save £180 off standard prices.</li>"`

returns 5

### Expected Behavior

should return 6

### Actual Incorrect Behavior

returns 5

**Comment by bryanlogan** [comment]
It looks like our `StringUtils.countOccurrences()` does have a bug where if the target is at the end of the string, it doesn't count it. It might be best to roll your own function for this until we get the fix released.

**Comment by bryanlogan** [comment]
This has been fixed in our internal repo and should be in the next release.
