### ISSUE TITLE
Configurable Log Level

### ISSUE THREAD

**Issue by MichaelEvans** [Appboy/appboy-android-sdk#27]
It'd be great if the log levels from the appboy jar were configurable somehow. My logcat is filled with stuff that I can't really understand/is useful like:

.bo.app.bv﹕ Completed the openSession call. Starting or continuing session xxxxxx
.bo.app.z﹕ Adding request to dispatcher with parameters
etc.

**Comment by briancaw** [comment]
Hi All,

We've enabled configurable log levels in 1.7.3 by setting the com.appboy.support.AppboyLogger.LogLevel value.

We're happy to hear any comments or questions regarding this solution.

- Appboy Android Team
