### ISSUE TITLE
NullPointerException when starting an Activity that implements iEventSubscriber

### ISSUE THREAD

**Issue by yishai-glide** [Appboy/appboy-android-sdk#34]
when trying to navigate into an Activity that implements IEventSubscriber I get a crash with the following logs:

```
02-15 15:38:34.146: W/dalvikvm(24719): threadid=36: thread exiting with uncaught exception (group=0x418afc08)
02-15 15:38:34.151: W/System.err(24719): java.lang.NullPointerException
02-15 15:38:34.151: W/System.err(24719): 	at com.my.package.MyActivity.trigger(SourceFile:103)
02-15 15:38:34.151: W/System.err(24719): 	at bo.app.az.run(SourceFile:266)
02-15 15:38:34.151: W/System.err(24719): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-15 15:38:34.151: W/System.err(24719): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-15 15:38:34.151: W/System.err(24719): 	at java.lang.Thread.run(Thread.java:841)
```

line#103 is the the first line of the class, and this looks like an issue on the Appboy SDK side of things.

**Comment by briancaw** [comment]
Thanks for reporting this Yishai - can you describe the entirety of your event subscription integration?  That line of code just called subscriber.trigger(), so the only NPE there would be if subscriber is null - I'll review our code there to make sure nothing might be causing that on our end; it might be good to double check that your Activity isn't becoming null somehow.  

More to that effect, you might look at https://github.com/Appboy/appboy-android-sdk/blob/c7b01b1ac8061a616496fc18013f18e4307e81b3/android-sdk-ui/src/com/appboy/ui/slideups/AppboySlideupManager.java to see how we subscribe to slideup events in our UI code.  Note that we subscribe when we register the SlideupManager onResumse and unsubscribe when we unregister the SlideupManager in onPause. I think that calling Appboy.getInstance(activity).removeSingleSubscription() at an appropriate time might solve your problem by removing your subscription before your Activity disappears.

Please let me know if that helps.

**Comment by yishai-glide** [comment]
the code that subscribes for updates is in the `onResume` method and is according to the documentation.
there is an un-subscription when the app goes through `onPause`.


here is the code snippet from this Activity
```
    @Override
    protected void onResume() {
        super.onResume();   
        Appboy.getInstance(this).requestFeedRefresh();
        AppboySlideupManager.getInstance().registerSlideupManager(this);
        AppboySlideupManager.getInstance().setCustomSlideupViewFactory(new SlideupFactory());
        AppboySlideupManager.getInstance().setCustomSlideupManagerListener(this);
        Appboy.getInstance(this).requestSlideupRefresh();
    }

    @Override
    protected void onPause() {
        super.onPause();
        AppboySlideupManager.getInstance().unregisterSlideupManager(this);
    }
```

**Comment by briancaw** [comment]
Sorry Yishai I'm not sure I follow here - I was referring to the SlideupManager as an example of a class we implement that manually subscribes and unsubscribes from subscriptions (and which creates a class that implements IEventSubscriber to do so).  I don't see anything in the code you pasted that manually calls a subscribeTo* method.  I was referring to the SlideupManager's onResume/onPause functionality as an example of how it prevents the subscriber from remaining set after the class is disposed of.

i.e.  Why/where are you implementing IEventSubscriber and manually using that class to subscribe to events?

**Comment by wendy-p** [comment]
Fyi, just got an email response from Yishai:

"Hi Wendy.

I'm sorry it took me so long to answer both you and him. I read the documentation and saw that implementing the IEventSubscriber doesn't automatically mean that the client will receive the information, but in order to get information from the Appboy admin panel there is a need to subscribe for updates.

this is something I do in the onResume method after everything is initialized and I cannot understand why my app crashed.
It might be me but I'm failing to understand what i did to cause this crash."

**Comment by briancaw** [comment]
Hi Yishai

We followed up offline and I think the issues you were seeing were not coming from our SDK.  We'll make sure documentation is as up-to-date as possible regarding this part of our integration, but I'm going to remove this as an issue on this repo.
