### ISSUE TITLE
Sources and javadoc in Maven Repo

### ISSUE THREAD

**Issue by hameno** [Appboy/appboy-android-sdk#36]
Hi,
it would be really helpful if the sources and javadoc could be deployed to the maven repo.

**Comment by briancaw** [comment]
Hi again @hameno 

We don't currently release our private library source, though it's certainly something that is under consideration.  In lieu of releasing the source, we hope that our javadocs, open source UI code, documentation, and integration sample projects are sufficient to make our libraries as easy to use as possible.  If there's a particular design decision or under-the-hood functionality you have questions about, we'd be happy to answer any questions.

**Comment by hameno** [comment]
Hi, 
not releasing the private library is okay. But the javadoc and sources of this reposiroty should be deployed to the maven repo so you can actually read the documentation within the IDE and not search for it in the browser which is slow and cumbersome.

**Comment by briancaw** [comment]
Is https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/javadocs what you're looking for?

i.e. The javadocs live in this repo under the gh-pages branch in the javadocs folder.

**Comment by hameno** [comment]
No, it is common to deploy a sources.jar and a javadoc.jar to the maven repo. Those artifacts will be automatically downloaded by the IDE and used to display documentation for every method.

**Comment by briancaw** [comment]
Thanks for clarifying @hameno.  We'll have this functionality added in the near future; we'll update with a release timeline when we have one.

**Comment by hameno** [comment]
Great

**Comment by briancaw** [comment]
Note:  also tracking https://github.com/Appboy/appboy-android-sdk/issues/37 here - i.e. getting UI javadocs.

**Comment by briancaw** [comment]
Hi @hameno 

We've added the UI library to our javadocs.

You can get the source here: https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/javadocs.
You can see them here: http://appboy.github.io/appboy-android-sdk/javadocs/.

Regarding the sources/javadocs jars:

1)  For the javadocs jars, the latest Android Studio supports attaching a javadoc source from either a local or remote path.  That seems to be the preferred way of javadoc integration and this release supports that.  We think adding a separate jar would add complexity for an increasingly uncommon use-case.

2)  For the sources jars:
  - Our private library is obfuscated, so having a sources jar there would either provide no value or break our obfuscation
  - Our UI library is open source.  We think the added complexity and case-wise requirements of adding a UI sources jar isn't ideal, especially when folks can just download the UI sources and point at them if needed.

Thanks again very much for raising these issues to our attention.  We welcome any additional feedback on the solution we've provided and hope you continue to help us make the best product possible.

- Appboy Android team
