### ISSUE TITLE
Javadoc outdated

### ISSUE THREAD

**Issue by hameno** [Appboy/appboy-android-sdk#37]
The linked javadoc is outdated and does not include the new AppboySlideupManager

**Comment by briancaw** [comment]
Hi @hameno 

AppboySlideupManager is in our UI code whose source lives in this repo.  We currently don't generate javadocs for our UI code.  If that's something you'd find useful please let us know and we can consider adding them in a future release.

https://github.com/Appboy/appboy-android-sdk/blob/master/android-sdk-ui/src/com/appboy/ui/slideups/AppboySlideupManager.java

**Comment by hameno** [comment]
Yes, as I mentioned in the other issue it the source and javadoc should be deployed to the maven repo for easier use.

**Comment by briancaw** [comment]
Hi @hameno 

Closing this issue and tracking both in https://github.com/Appboy/appboy-android-sdk/issues/36.

Thanks,
Brian
