### ISSUE TITLE
Android Studio - android-sdk-ui not downloading properly with Gradle

### ISSUE THREAD

**Issue by nscastelli** [Appboy/appboy-android-sdk#41]
I've been trying to install android-sdk-ui with Gradle following the steps detailed [here](https://documentation.appboy.com/SDK_Integration/Android_and_FireOS#integrate-with-android-studio). However, the downloaded package is not android-sdk-**ui** but android-sdk-**jar**.

Because of this, I'm not being able to use, for example, AppboyFeedbackFragment.

More info: I don't know if it has to do with this issue, but in [this maven-metadata](http://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui/maven-metadata.xml) file, the artifactId is android-sdk-jar, (not "ui"). 

Thanks in advance!

**Comment by yishai-glide** [comment]
there's an aar file in the repo, you can use it in the build.gradle and it should work just fine

**Comment by briancaw** [comment]
Hi @nscastelli,

Which part of those docs are you using to integrate - installing locally or just pulling from the remote repo?  We haven't seen this issue before with either method, but we'll double check with your environment information.  Can you let us know what AS version and gradle version you are using?

Regarding that maven metadata file - I've gone and updated that artifactId there.  If things are fixed after that change we'd still very much appreciate knowing the version numbers and integration method that triggered this error.

Thanks for reporting and thanks @yishai-glide for giving the info on the aar.

**Comment by nscastelli** [comment]
Hi @briancaw,

I'm trying to pull from the remote repo, using AS 1.2.1.1 and Gradle 2.4. The update to the metadata file didn't change anything.

However, I managed to import the library via the .aar file just as @yishai-glide said. Thank you.

**Comment by nscastelli** [comment]
Hi @briancaw,

After performing a "Clean project", I was able to retrieve your library from the remote properly, so it wasn't a problem in the library itself. Sorry and thank you!

**Comment by briancaw** [comment]
That's great to hear @nscastelli, thanks for the update.  Glad everything is working - please feel free to reach out if you have any other issues!
