### ISSUE TITLE
java.lang.RuntimeException: Unknown exception code: 1 msg null

### ISSUE THREAD

**Issue by sanjay-tinyowl** [Appboy/appboy-android-sdk#42]
We are having this issue on specific devices such as Lenovo A6000 or A680 ROW (Android v4.4.4, v4.2.2).

Here is the crash log:

Caused by: java.lang.RuntimeException: Unknown exception code: 1 msg null
       at android.os.Parcel.readException(Parcel.java:1477)
       at android.os.Parcel.readException(Parcel.java:1419)
       at android.app.ActivityManagerProxy.checkPermission(ActivityManagerNative.java:3457)
       at android.app.ContextImpl.checkPermission(ContextImpl.java:1686)
       at android.app.ContextImpl.checkCallingOrSelfPermission(ContextImpl.java:1712)
       at android.content.ContextWrapper.checkCallingOrSelfPermission(ContextWrapper.java:555)
       at bo.app.bq.(SourceFile:52)
       at bo.app.ei.(SourceFile:103)
       at com.appboy.Appboy.(SourceFile:324)
       at com.appboy.Appboy.getInstance(SourceFile:133)

We are using Appboy 1.6.+ library.

We are not sure using latest library can resolve the issue reported above. Please provide us your feedback.

Thanks,
Sanjay

**Comment by sanjay-tinyowl** [comment]
Hello,

We have been experiencing this issue on our last 8 releases and consistently appearing on the devices I listed in my earlier comment. I do understand that every OEM has its own fork of Android OS but during my findings, similar issue was also reported for paypal sdk (https://github.com/paypal/PayPal-Android-SDK/issues/167) but can't see how they resolved this issue. So this issue is actually not related to Android OS but perhaps the issue with the way it is implemented.

Appreciate if this issue can be resolved as this is the second most crashes in our last 8 releases. Surely provide more info as I get any more breakthroughs or insights.

Thanks,
Sanjay

**Comment by briancaw** [comment]
Thanks for the update and additional information Sanjay - we should have a fix for this in our next release (early next week).  I"ll update when that's live.

Thanks,
Brian

**Comment by sanjay-tinyowl** [comment]
Cool!! Looking forward to the fix and use the latest Appboy library whenever available.

Thanks again,
Sanjay

**Comment by sanjay-tinyowl** [comment]
Hello Brian,

Was this issue fixed? Please update.

Thanks,
Sanjay

**Comment by briancaw** [comment]
Hi @sanjay-tinyowl 

It is fixed on our development branch but we haven't released it yet.  We're aiming to release early next week.  

Thanks,
Brian

**Comment by briancaw** [comment]
Hi @sanjay-tinyowl 

This is fixed in this most recent release.

Thanks,
Brian

**Comment by sanjay-tinyowl** [comment]
Thanks you so much Brian!! I'll keep you updated if I find this issue again or any other issues.

Appreciate for your quick action.
- Sanjay

**Comment by jiaxin262** [comment]
hi, I wanna know how you fix this, however I can not find the code com.appboy.support.PermissionUtils;

**Comment by briancaw** [comment]
Hi @jiaxin262 

That code is in our base library which isn't open source.  The hasPermission method looks like:

```
  public static boolean hasPermission(Context context, String permission) {
    try {
      return context.checkCallingOrSelfPermission(permission) == PackageManager.PERMISSION_GRANTED;
    } catch (Throwable t) {
      AppboyLogger.e(TAG, String.format("Failure checking permission %s", permission), t);
      return false;
    }
  }
```

**Comment by jiaxin262** [comment]
@briancaw very grateful !

**Comment by rahulrvp** [comment]
@briancaw Thanks a lot for the code snippet! It definitely saved at least a couple of hours of mine :)
