### ISSUE TITLE
Proguard Rules

### ISSUE THREAD

**Issue by MichaelEvans** [Appboy/appboy-android-sdk#43]
Do you have a recommended list of what can be safely proguarded/ignored/etc?

I get a lot of warnings from various classes related to `.gms.wearable.*`, `com.facebook.fresco.*`, etc.

**Comment by briancaw** [comment]
Hi @MichaelEvans 

You can see our updated proguard rules for 1.9.2 here:

https://documentation.appboy.com/SDK_Integration/Android_and_FireOS#proguard

There's also some notes about the additions here:  https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md
