### ISSUE TITLE
Unable to Integrate the news feed in android (Need help)

### ISSUE THREAD

**Issue by SureshKispotta** [Appboy/appboy-android-sdk#60]
Hey how to integrate the News feed in android app  But it is not working in a android (Need Help)

**Comment by radixdev** [comment]
Hello @SureshKispotta,

Can you let us know where in the documentation found [here](https://www.appboy.com/documentation/Android/#news-feed) you're running into issues?

Can you also let us know:
1. How are you integrating the News Feed in your app?
2. What is the bug you're experiencing?
3. Any other details to help us debug this issue.

Thanks,
Appboy Android Team

**Comment by radixdev** [comment]
Hey @SureshKispotta,

Just pinging on this - it would be great to help you debug this issue and we'd very much appreciate any info you might be able to provide.

Thanks,
Appboy Android Team

**Comment by radixdev** [comment]
Hey @SureshKispotta ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
