### ISSUE TITLE
How to switch API keys in different build variants?

### ISSUE THREAD

**Issue by virtualandy** [Appboy/appboy-android-sdk#65]
Lowly question - I want to use a different API key in different build variants of our app, i.e. dev/staging use one Appboy key, production uses another.

Since the key goes in `res/values/appboy.xml` I'm a bit confused as to how to do that properly. Any ideas?

**Comment by radixdev** [comment]
Hey @virtualandy,

The recommended way to change your API key in different variants is to use the Appboy.configure() method. You can provide a different API key based on the flavor. See our [configure() javadocs for more info](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/Appboy.html#configure-android.content.Context-java.lang.String-). Additionally, see our Droidboy sample app for [an example](https://github.com/Appboy/appboy-android-sdk/blob/master/droidboy/src/com/appboy/sample/DroidboyApplication.java#L47) of how we set a different API key based on the build flavor. 

Let me know if this solves your use case and if you have any further questions.

Thanks,
Appboy Android Team

**Comment by virtualandy** [comment]
@radixdev ah, perfect. I hoped there was something like that but missed it.

Will check out those examples and close this up.

On another note, also tried putting a new `appboy.xml` file in `app/src/release/res/values`. Would that also work?

**Comment by radixdev** [comment]
Glad to hear it. 

Also, putting a new appboy.xml file in your flavor's values folder would also definitely work. Any configuration values in that new appboy.xml would override your default xml, so if you included a different API key in that file it would work.

**Comment by virtualandy** [comment]
@radixdev awesome, thanks for the follow up.
