### ISSUE TITLE
How to fetch campaign_id from IAM?

### ISSUE THREAD

**Issue by ernestkamara** [Appboy/appboy-android-sdk#70]
Hi guys,
I have a CustomIInAppMessageManagerListener and trying to log all IAM related events to our servers. 

Retrieving the `campaign_id` from `IInAppMessage.forJsonPut().getString(AppboyGcmReceiver.CAMPAIGN_ID_KEY);`
 returns null. 

I am not sure if i am doing something wrong here, but seems to be true since there is no KEY with AppboyGcmReceiver.CAMPAIGN_ID_KEY in the IInAppMessage Json below.

`{"message":"Nulla consequat massa quis enim. Donec pede justo,\nfringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut,\nimperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium.\nInteger tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate\neleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac,","type":"MODAL","text_color":4280624421,"text_align_message":"CENTER","click_action":"NEWS_FEED","message_close":"SWIPE","header":"This is how to share","header_text_color":4280624421,"text_align_header":"CENTER","image_url":"https:\/\/appboy-images.com\/appboy\/communication\/marketing\/slide_up\/slide_up_message_parameters\/images\/584fdd8656ec317ebe6cc4d9\/6727b80948ccfe3ba042da1a670c1fc9f2ca1703\/original.?1481629066","image_style":"TOP","close_btn_color":4291085508,"bg_color":4294440951,"frame_color":3207803699,"btns":[{"text":"OK","bg_color":4279990479,"text_color":4294967295,"click_action":"NONE","id":0}],"trigger_id":"NTg0ZmRkODY1NmVjMzE3ZWJlNmNjNGNmXzU4NGZkZDg2NTZlYzMxN2ViZTZjYzRkNV9jbXA="}`

I suspect the `trigger_id` to be the `campaign_id`, am I that correct?
With that said, what is the different between Push `campaign_id` & IAM `trigger_id`?

**Comment by Bucimis** [comment]
Hi @ernestkamara,

Thanks for filing this issue.

Although it's technically possible to retrieve analytics Ids from in-app messages, we recommend not doing so as they are considered private API and subject to change. The field used for the id, the format of the id, and how the id is delivered may potentially change at any time.

Unfortunately we don't have a plan for supporting a public analytics id at this time.

For storage in your own systems, you might consider alternatives like generating your own ids or deriving an id from the message.

Thanks,
Jared

**Comment by ernestkamara** [comment]
Thank you for your quick response @Bucimis.
I would discuss this issue further with my team.
 
Thanks,
Ernest.

**Comment by Bucimis** [comment]
Sounds good, thanks @ernestkamara.
