### ISSUE TITLE
Upgrade to 1.19.0, APPBOY_ACTION_IS_CUSTOM_ACTION_KEY can't be found

### ISSUE THREAD

**Issue by plastic-kai** [Appboy/appboy-android-sdk#73]
I just upgraded appboy to 1.19.0. Used to have the following code:

`if (intent.getBooleanExtra(Constants.APPBOY_ACTION_IS_CUSTOM_ACTION_KEY, false)) {
                    //Toast.makeText(, "You clicked a Droidboy custom action!", Toast.LENGTH_LONG).show();
                } else {`

now it says "APPBOY_ACTION_IS_CUSTOM_ACTION_KEY" can't be found.

**Comment by radixdev** [comment]
Hello @plastic-kai,

Thanks for filing this issue. In 1.19.0 we removed custom notification action buttons and as a result that constant was also removed. Please see the [changelog](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md) for information.

Cheers,
Appboy Android Team

**Comment by plastic-kai** [comment]
Hi radixdev, 

thanks for the quick reply. so, what shall I do to make that part of code work?

`if (intent.getBooleanExtra(Constants.APPBOY_ACTION_IS_CUSTOM_ACTION_KEY, false)) { //Toast.makeText(, "You clicked a Droidboy custom action!", Toast.LENGTH_LONG).show(); } else {`

**Comment by radixdev** [comment]
Since that constant was removed in 1.19.0, I'd recommend just removing that logic from your app entirely for your code to continue to work on 1.19.0. 

Please let me know if you have any more questions or concerns.

**Comment by plastic-kai** [comment]
Thanks, radixdev. Now I know what it does and can safely remove those lines.
