### ISSUE TITLE
Remove hard dependency over Fresco

### ISSUE THREAD

**Issue by vannenc** [Appboy/appboy-android-sdk#76]
It would be just amazing if we could use our own image loading library without depending over Fresco. We already have Glide as default image loader, adding another image library means an increase in the method counts.

Glide already supports Gifs. The image loading part should be abstracted so that custom image loading libraries can be used.

**Comment by Bucimis** [comment]
Hi @vannenc 

Thanks for this feedback and agreed!  Providing non-Fresco alternatives for Gifs is one of our top priorities, although the current tight coupling in the SDK makes it fairly challenging from an engineering perspective.  We'll be investigating our alternatives/executing on this over the coming months and will be in touch as we do so.

For the time being, we recommend using Proguard to strip Fresco to the bare minimum referenced by Appboy.

Thanks!
Appboy Android Team

**Comment by mikkoville** [comment]
Hello

Is this still one of your top priorities? It has been quite some time from last may. Do you have any metrics on how much does Proguard stripped Fresco increase method count or APK size?

Thank you

**Comment by radixdev** [comment]
Hey @mikkoville ,

Apologies for the late response. This is indeed still a large priority for us. Our SDK already has been laying the groundwork for the full removal of Fresco from the SDK with the addition of the [IAppboyImageLoader](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/IAppboyImageLoader.html). This image loading handler currently renders/retrieves images for push notifications and the news feed. A custom loader can be set [here on the singleton](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/Appboy.html#setAppboyImageLoader-com.appboy.IAppboyImageLoader-). Fully replacing Fresco with this loader is our goal as well as an example integration with it and Glide. 

For Fresco proguard metrics, I'd visit their [FAQ](http://frescolib.org/docs/faq.html).

**Comment by radixdev** [comment]
Hello @vannenc , @mikkoville , @sofiahellofresh , @fernandagallina , @siempredelao , @AaronRietschlin , @keith30xi , @ivngrz , @spinillos 

We're happy to announce that the Braze Android SDK (as of [SDK version 2.2.3](https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#223)) now fully supports custom image libraries for push, in-app messages, and the News Feed. GIFs can now be rendered using Glide, Fresco, or any other image library. Custom image library functionality is encapsulated in the [IAppboyImageLoader](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/IAppboyImageLoader.html) interface. This interface is set on the Braze singleton via the [setAppboyImageLoader](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/IAppboy.html#setAppboyImageLoader-com.appboy.IAppboyImageLoader-) method.

For an example of how to set an [IAppboyImageLoader](http://appboy.github.io/appboy-android-sdk/javadocs/com/appboy/IAppboyImageLoader.html), we have also added the [Glide Image Integration Sample App](https://github.com/Appboy/appboy-android-sdk/tree/master/samples/glide-image-integration). The Glide IAppboyImageLoader interface can be found in that sample app in the [GlideAppboyImageLoader sample integration class](https://github.com/Appboy/appboy-android-sdk/blob/master/samples/glide-image-integration/src/main/java/com/appboy/glideimageintegration/GlideAppboyImageLoader.java).

Apologies again for the long delay in releasing this functionality. Please let us know any suggestions for improvement to this interface.

Thanks,
Braze Android Team

**Comment by spinillos** [comment]
@radixdev Thank you too much 😄

**Comment by radixdev** [comment]
Hello all,

I'm closing this issue for now. Please let me know if any of you continue to have issues and we'll debug further.
