### ISSUE TITLE
Make AppboyFeedManager non-final. 

### ISSUE THREAD

**Issue by Nemisis** [Appboy/appboy-android-sdk#78]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Appboy Android SDK are you using?
2.0.4

## What did you do?
Integrated the Appboy SDK into our project and wanted to set a custom click listener via `IFeedClickActionListener` on the `AppboyFeedManager` class. 

## What did you expect to happen?
Ideally, it would be a non-final class to allow for mocking. 

## What happened instead?
The registration works properly. However, it is a final class which makes it difficult to mock and therefore test in isolation due to the requirement that the Appboy SDK be initialized. 

## Steps to reproduce
* Create a JUnit test with Mockito
* Set up a mock instance of `AppboyFeedManager`, e.g.: `@Mock AppboyFeedManager mockFeedManager`. 
* Run your test. Note, it will fail due to it being a final class.

**Comment by Bucimis** [comment]
Hi @Nemisis,

Seems eminently sensible. We've made the change and it will be available in our next release.  We'll reping at release time - should be within 1-2 weeks.

Thanks!
Appboy Android Team

**Comment by Bucimis** [comment]
@Nemisis this is released! Thanks again
