### ISSUE TITLE
Update Fresco version 

### ISSUE THREAD

**Issue by keith30xi** [Appboy/appboy-android-sdk#79]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Appboy Android SDK are you using?
2.0.4

## What did you do?
The samples refer to Fresco 0.9

See https://github.com/Appboy/appboy-android-sdk/blob/77882b360c9318ccde65f980c844d3fbb483f781/gradle.properties

Because this pulls in some transitive dependencies that we cannot use due to other issues, we attempted to update to Fresco 1.3.0.  It appears that Fresco has split out parts into multiple Fresco modules.  

Can you update the sample projects to use this updated version of Fresco?  

```
  compile 'com.appboy:android-sdk-ui:2.0.4'
  compile 'com.facebook.fresco:fresco:1.3.0'
  compile 'com.facebook.fresco:animated-gif:1.3.0'
```

Other libraries may also be needed depending on sample project needs (e.g., WebP images).

http://frescolib.org/docs/index.html

**Comment by Bucimis** [comment]
Hi @keith30xi,

Thanks for filing this issue. We'll update our sample apps to use the latest version of Fresco for our next release, which should be within 1-2 weeks.

In your own app project, you should be able to use Fresco `1.3.0` with the current Appboy Android SDK release right away.

Let us know if you have any further questions or concerns.

Thanks!
Appboy Android Team

**Comment by Bucimis** [comment]
Hi @keith30xi,

The sample apps have been updated. Please see https://github.com/Appboy/appboy-android-sdk/blob/master/droidboy/build.gradle#L15 and https://github.com/Appboy/appboy-android-sdk/blob/master/gradle.properties#L8

Thanks again!
Appboy Android Team
