### ISSUE TITLE
Maven Metadata Changed

### ISSUE THREAD

**Issue by Yuliya-Kaleda** [Appboy/appboy-android-sdk#84]
When building our Android app we have an error being thrown:
 
23:46:50 FAILURE: Build failed with an exception.
23:46:50
23:46:50 * What went wrong:
23:46:50 A problem occurred configuring project ':app'.
23:46:50 > Could not resolve all dependencies for configuration ':app:_appDebugApk'.
23:46:50    > A problem occurred configuring project ':plplib'.
23:46:50       > Could not resolve all dependencies for configuration ':plplib:_appDebugPublish'.
23:46:50          > A problem occurred configuring project ':baselib'.
23:46:50             > Could not resolve all dependencies for configuration ':baselib:_appDebugPublishCopy'.
23:46:50                > Could not find any version that matches com.appboy:android-sdk-ui:[2.0,2.1).
23:46:50                  Versions that do not match:
23:46:50                      2.2.1
23:46:50                  Required by:
23:46:50                      project :baselib > com.mparticle:android-appboy-kit:4.16.0
23:46:50
 
Seems like maven metadata got recently changed and is not generated properly (it does not have all versions listed).

Currently used Appboy SDK version is 2.1.4

Thank you!

**Comment by Bucimis** [comment]
@Yuliya-Kaleda thanks for alerting us to this - spot on diagnosis. Metadata should be fixed now, please let us know if it fixes things on your end.

**Comment by Yuliya-Kaleda** [comment]
@Bucimis thank you for a quick fix, things work on our end!

**Comment by Bucimis** [comment]
@Yuliya-Kaleda great to hear! apologies for the inconvenience and thanks again for filing!
