### ISSUE TITLE
 Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=.AppboyGcmReceiver (has extras) }

### ISSUE THREAD

**Issue by Rahulrsannidhi** [Appboy/appboy-android-sdk#86]
In our Application, we are using the version 2.0.5 now getting the lot of ANR report from google play developer console 
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=com.app cmp=com.app/com.appboy.AppboyGcmReceiver (has extras).

Broadcast of Intent { act=com.appboy.action.APPBOY_PUSH_CLICKED flg=0x10 cmp=com.app/com.appboy.AppboyGcmReceiver (has extras) }

**Comment by Bucimis** [comment]
Hi @Rahulrsannidhi,

Thanks for bringing this issue to our attention. Do you have any more information on the numbers of ANRs, as well as any general information on the types/versions of devices affected? Feel free to forward any more information that could be helpful for our investigation as well.

Thanks,
Appboy Android Team

**Comment by Rahulrsannidhi** [comment]
Thanks for the reply here am  attaching the some of the screen shots from the google play reports.
![screenshot2017-12-14at12 31 11pm_edit](https://user-images.githubusercontent.com/1352289/33986154-cab6ca08-e0cd-11e7-87bc-52e31e1198ed.jpg)
![screenshot2017-12-14at12 34 28pm_edit2](https://user-images.githubusercontent.com/1352289/33986158-cbec6522-e0cd-11e7-9eec-deae13035b6c.jpg)
![screenshot2017-12-14at12 54 25pm_edit_3](https://user-images.githubusercontent.com/1352289/33986363-5c50466a-e0ce-11e7-8be9-6f899efef753.jpg)
hope this will help to track the issue.

**Comment by Bucimis** [comment]
Hi @Rahulrsannidhi,

Thank you for compiling this information for us. We've noticed that you're obscuring your package name in these screenshots.

It would be great to resolve this in a more private setting (e.g. so you don't need to obscure your package name, send us builds, etc). Please email your CSM or support@braze.com to open a ticket so we can continue this conversation.

One further question, we noticed that Appboy is not in the stacktrace provided. Is that a common theme across the ANR stacktraces?

Thanks,
Appboy Android Team

**Comment by radixdev** [comment]
Hey @Rahulrsannidhi ,

Any updates on this issue?

**Comment by radixdev** [comment]
Hey @Rahulrsannidhi ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
