### ISSUE TITLE
Agree

### ISSUE THREAD

**Issue by tigermuda83** [Appboy/appboy-android-sdk#87]
* [ ] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

**Comment by tigermuda83** [comment]
I kiked it

**Comment by Bucimis** [comment]
Hi @tigermuda83,

Did you perhaps open this issue by mistake?

If you are experiencing an issue with the android sdk, please open a new ticket with details. We would be happy to help.

Thanks,
Appboy Android Team
