### ISSUE TITLE
Feed data shouldn't be stored in SharedPreferences

### ISSUE THREAD

**Issue by shaishavgandhi05** [Appboy/appboy-android-sdk#93]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
2.2.1

## What is the issue?

In-App notification feed cards are being stored in SharedPreferences of the application. The whole list of Feed cards are being stored in SharedPreferences as a whole blob. SharedPreferences aren't a place to store large amount of data. Also, as the feed cards increase (i.e we send more in app notifications), the data will increase. SharedPreferences are loaded into memory on app start and this is affecting app start times. 

The SharedPreference file name: `com.appboy.storage.feedstorageprovider.*`
Key: `cards`
Value : LARGE BLOB.

I'm not sure if i should post the value of the feed cards here. But I can privately share it.

**Comment by radixdev** [comment]
Hello @shaishavgandhi05 ,

Thanks for filing this issue. We have upcoming changes on our roadmap for the News Feed that should reduce any hiccups in performance when viewing cards. Through testing, we've seen that performance degrades linearly but should be robust in the <500 cards range.

Approximately how many cards are being kept your News Feed? Can you elaborate on "we send more in app notifications"?

**Comment by shaishavgandhi05** [comment]
Right now we have close to 15 news feed cards. We're planning on increasing the amount of feed cards we send, so this number will increase.

The performance degradation is mostly seen on application start when shared preferences are brought into memory by Android.

**Comment by radixdev** [comment]
15 cards is well within the expected range of cards where we don't anticipate any performance drops so I would like to ask a few more questions to properly debug the issue:

1. Can you estimate the scale/time of the performance drop?
2. How large is the size of a single News Feed item?
3. What types/models of devices is this performance drop occurring on?

**Comment by radixdev** [comment]
I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
