### ISSUE TITLE
Remove unnecessary code from AppboyUnityPlayerNativeActivity [Important]

### ISSUE THREAD

**Issue by MartinGonzalez** [Appboy/appboy-android-sdk#95]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

## What version of the Braze Android SDK are you using?
2.1.4

## What I want?

First of all thanks for taking your time to read this issue. My request is to do some changes in `AppboyUnityPlayerNativeActivity` to allow **flexibility** with other implementations and professionalism in the service provided..

- Extend from `UnityPlayerActivity` and **not** from `UnityPlayerNativeActivity`, this one and `UnityPlayerProxyActivity` are deprecated since Unity 3.4.

- Remove code that forces you to use appboy activity as the main activity

In `AppboyUnityPlayerNativeActivity.java`

```java
  public void logInAppMessageClick(String messageJSONString) {
    mAppboyUnityPlayerNativeActivityWrapper.logInAppMessageClick(messageJSONString, this);
  }

  public void logInAppMessageButtonClick(String messageJSONString, int buttonId) {
    mAppboyUnityPlayerNativeActivityWrapper.logInAppMessageButtonClick(messageJSONString, buttonId, this);
  }

  public void logInAppMessageImpression(String messageJSONString) {
    mAppboyUnityPlayerNativeActivityWrapper.logInAppMessageImpression(messageJSONString, this);
  }
```

In `AppBoyBinding.cs` Instead of calling directly to the Activity please call to `mAppboyUnityPlayerNativeActivityWrapper`.

```c#
 public static void LogInAppMessageClicked(string inAppMessageJSONString) {
      AppboyUnityActivity.Call("logInAppMessageClick", new object[] { inAppMessageJSONString });
    }

    public static void LogInAppMessageImpression(string inAppMessageJSONString) {
      AppboyUnityActivity.Call("logInAppMessageImpression", new object[] { inAppMessageJSONString });
    }
    
    public static void LogInAppMessageButtonClicked(string inAppMessageJSONString, int buttonID) {
      AppboyUnityActivity.Call("logInAppMessageButtonClick", new object[] { inAppMessageJSONString, buttonID });
    }

    [System.Obsolete("LogSlideupClicked is deprecated, please use LogInAppMessageClicked instead.")]
    public static void LogSlideupClicked(string slideupJSONString) {
      AppboyUnityActivity.Call("logInAppMessageClick", new object[] { slideupJSONString });
    }

    [System.Obsolete("LogSlideupImpression is deprecated, please use LogInAppMessageImpression instead.")]
    public static void LogSlideupImpression(string slideupJSONString) {
      AppboyUnityActivity.Call("logInAppMessageImpression", new object[] { slideupJSONString });
    }
```

## Result

Doing this will allow users to implement ActivityListeners **(Objects that will listen Activity lifecycle)** without being force to change your code or use your own main activity.

Thanks!

**Comment by MartinGonzalez** [comment]
@radixdev Nice! Please remember to remove `LogInAppXXX` methods from the activity too! :D

Thanks!

**Comment by radixdev** [comment]
Hello @MartinGonzalez ,

We've updated the unity portion of this repo's codebase, see [here](https://github.com/Appboy/appboy-android-sdk/tree/master/android-sdk-unity/src/com/appboy/unity). The `AppboyBinding.cs` will have to be made in the unity repo to go into effect.

**Comment by Bucimis** [comment]
this is done, thanks again @MartinGonzalez
