### ISSUE TITLE
Our App uses GCM via Appboy, still I am getting crash reports related to Firebase "Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.MESSAGING_EVENT"

### ISSUE THREAD

**Issue by AarshiG** [Appboy/appboy-android-sdk#96]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/Android/) and am still experiencing the issue.

# Report

**Comment by radixdev** [comment]
1. What version of the Braze Android SDK are you using? What version of the support library are you using?
2. On what device did this crash happen?
2. Can you provide steps to reproduce?
3. Can you share your `AndroidManifest`?
4. Can you share your main app's `build.gradle`?
5. Can you share the your gradle dependencies for your main app module? I.e. `./gradlew :app:dependencies` where `app` is the module for your application.

**Comment by AarshiG** [comment]
1. Can you pls let me know how I can check the version number? We are using the module android-sdk-ui since we have customisations that we had to perform

2.It is happening on Android Oreo only

3.java.lang.IllegalStateException: Unable to start receiver com.google.firebase.iid.FirebaseInstanceIdReceiver: java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.firebase.MESSAGING_EVENT pkg=<app_package> cmp=<app_package>/com.google.firebase.messaging.FirebaseMessagingService (has extras) }: app is in background uid UidRecord{2efe012 u0a0 RCVR bg:+13m40s64ms idle procs:1 seq(0,0,0)}

4. <receiver
            android:name="com.appboy.AppboyGcmReceiver"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>

                <category android:name="<package_name>"/>
            </intent-filter>
        </receiver>
        <receiver
            android:name=".AppboyBroadcastReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="<package_name>.intent.APPBOY_PUSH_RECEIVED"/>
                <action android:name="<package_name>.intent.APPBOY_NOTIFICATION_OPENED"/>
            </intent-filter>
        </receiver>

        <activity
            android:name="com.appboy.ui.AppboyWebViewActivity"
            android:screenOrientation="portrait"
            android:theme="@android:style/Theme"/>
        <activity
            android:name="com.appboy.ui.activities.AppboyFeedActivity"
            android:screenOrientation="portrait"
            android:theme="@android:style/Theme"/>

5. compile 'com.android.support:multidex:1.0.0'
    androidTestCompile 'com.android.support:multidex-instrumentation:1.0.1'
    compile('com.github.nkzawa:socket.io-client:+') {
        exclude group: 'org.json'
    }
    compile project(':android-sdk-ui')
    androidTestCompile 'junit:junit:4.12'
    compile files('libs/Nanigans_SDK.jar')
    compile files('libs/GoogleConversionTrackingSdk-2.2.4.jar')
    compile files('libs/apptimize-android-2.13.5.jar')
    compile 'com.kochava.base:tracker:3.1.1'
    compile 'org.jsoup:jsoup:1.8.3'
    compile "com.android.support:design:${SUPPORT_PACKAGE_VERSION}"
    compile "com.android.support:support-v4:${SUPPORT_PACKAGE_VERSION}"
    compile "com.android.support:appcompat-v7:${SUPPORT_PACKAGE_VERSION}"
    compile "com.android.support:recyclerview-v7:${SUPPORT_PACKAGE_VERSION}"
    compile "com.google.android.gms:play-services-analytics:${GOOGLE_PLAY_SERVICES_VERSION}"
    compile "com.google.android.gms:play-services-wallet:${GOOGLE_PLAY_SERVICES_VERSION}"
    compile "com.google.android.gms:play-services-auth:${GOOGLE_PLAY_SERVICES_VERSION}"
    compile "com.google.android.gms:play-services-appindexing:${GOOGLE_PLAY_SERVICES_VERSION}"
    compile 'fr.avianey.com.viewpagerindicator:library:2.4.1@aar'
    compile 'in.srain.cube:grid-view-with-header-footer:1.0.12'
    compile 'com.facebook.android:facebook-android-sdk:4.26.0'
    compile 'io.card:android-sdk:5.5.1'
    compile 'com.squareup.picasso:picasso:2.5.0'
    compile 'com.usebutton:android-sdk:5.14.0'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile(name: 'visacheckout-android-sdk-5.5.2', ext: 'aar')
    compile "com.android.support:customtabs:${SUPPORT_PACKAGE_VERSION}"
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support:cardview-v7:21.0.+'

    androidTestCompile ('com.android.support.test:runner:0.4') {
        // Necessary if your app targets Marshmallow (since the test runner
        // hasn't moved to Marshmallow yet)
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile ('com.android.support.test:rules:0.4') {
        // Necessary if your app targets Marshmallow (since the test runner
        // hasn't moved to Marshmallow yet)
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    androidTestCompile ('com.android.support.test.espresso:espresso-core:2.2.2'){
        // Necessary if your app targets Marshmallow (since the test runner
        // hasn't moved to Marshmallow yet)
        exclude group: 'com.android.support', module: 'support-annotations'
    }

SUPPORT_PACKAGE_VERSION=24.2.0
GOOGLE_PLAY_SERVICES_VERSION=9.2.1

**Comment by AarshiG** [comment]
gradle file of android-sdk-ui look like this 

apply plugin: 'com.android.library'

dependencies {
  compile 'com.appboy:android-sdk-base:2.1.4'
  compile 'com.android.support:support-v4:26.0.1'
  provided ("com.facebook.fresco:fresco:1.3.0") {
    exclude group: 'com.android.support', module: 'support-v4'
  }
}

android {
  compileSdkVersion 26
  buildToolsVersion '26.0.1'

  defaultConfig {
    minSdkVersion 17
    targetSdkVersion 26
    consumerProguardFiles 'appboy-proguard-rules.pro'
  }

  sourceSets {
    main.setRoot(".")
    // Note: We'll be moving this project to the new Android Build System conventional folder structure in a future
    // release.
    main {
      manifest.srcFile 'AndroidManifest.xml'
      java.srcDirs = ['src']
      resources.srcDirs = ['src']
      aidl.srcDirs = ['src']
      renderscript.srcDirs = ['src']
      res.srcDirs = ['res']
      assets.srcDirs = ['assets']
    }
  }
}

**Comment by radixdev** [comment]
Hello @AarshiG ,

Any chance you can share the output of step 6? We don't import any Firebase dependencies as part of our SDK. In your error, the path for the receiver is `com.google.firebase.iid.FirebaseInstanceIdReceiver` which implies that a google dependency is the one causing the error, not the Braze SDK.

**Comment by radixdev** [comment]
Hey @AarshiG ,

I'm closing this issue for now. Please let me know if you continue to have issues and we'll debug further.
