### ISSUE TITLE
I'm unable to fetch the maven metadada from the provided URL 

### ISSUE THREAD

**Issue by gkaffka** [Appboy/appboy-android-sdk#97]
Hi, I'm having trouble fetching the maven metadata from the URL provided
`http://appboy.github.io/appboy-android-sdk/sdk/com/appboy/android-sdk-ui/maven-metadata.xml`
Is this URL still valid?

**Comment by radixdev** [comment]
Hello @gkaffka ,

We recently moved our gh-pages repo to `https`. Please change the url to `https`. Please let us know if this solves your issue.

**Comment by gkaffka** [comment]
Yes, all solved . 
Thank you for the quick answer!
